<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Endpoint;

class V1FolderIdStockUtilitiesProductionOrderNeedAllocation extends \Cegid\Api\Runtime\Client\BaseEndpoint implements \Cegid\Api\Runtime\Client\Endpoint
{
    use \Cegid\Api\Runtime\Client\EndpointTrait;
    protected $folderId;
    protected $workType;
    protected $productionOrder;
    protected $phase;
    protected $nomenclatureLink;

    /**
     * @param string                                                        $folderId             Identifiant de dossier
     * @param string                                                        $workType             Code de nature de travail
     * @param int                                                           $productionOrder      Numéro d'ordre de production
     * @param string                                                        $phase                Code de la phase
     * @param int                                                           $nomenclatureLink     Numéro de lien de nomenclature
     * @param \Cegid\Api\Model\CegidMtsStockModelsStockAllocationParameters $allocationParameters Liste des détails de stock à affecter + quantité
     */
    public function __construct(string $folderId, string $workType, int $productionOrder, string $phase, int $nomenclatureLink, \Cegid\Api\Model\CegidMtsStockModelsStockAllocationParameters $allocationParameters)
    {
        $this->folderId = $folderId;
        $this->workType = $workType;
        $this->productionOrder = $productionOrder;
        $this->phase = $phase;
        $this->nomenclatureLink = $nomenclatureLink;
        $this->body = $allocationParameters;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return str_replace(['{folderId}', '{workType}', '{productionOrder}', '{phase}', '{nomenclatureLink}'], [$this->folderId, $this->workType, $this->productionOrder, $this->phase, $this->nomenclatureLink], '/api/v1/{folderId}/stock/utilities/allocation/productionOrder/{workType}/{productionOrder}/phase/{phase}/need/{nomenclatureLink}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return $this->getSerializedBody($serializer);
    }

    /**
     * @return null
     *
     * @throws \Cegid\Api\Exception\UnexpectedStatusCodeException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (204 === $status) {
            return null;
        }
        throw new \Cegid\Api\Exception\UnexpectedStatusCodeException($status, $body);
    }

    public function getAuthenticationScopes(): array
    {
        return [];
    }
}
