<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsProductEntityUserDefinedTextsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsProductEntityUserDefinedTexts();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('UserDefinedText1', $data) && $data['UserDefinedText1'] !== null) {
                $object->setUserDefinedText1($data['UserDefinedText1']);
            } elseif (\array_key_exists('UserDefinedText1', $data) && $data['UserDefinedText1'] === null) {
                $object->setUserDefinedText1(null);
            }
            if (\array_key_exists('UserDefinedText2', $data) && $data['UserDefinedText2'] !== null) {
                $object->setUserDefinedText2($data['UserDefinedText2']);
            } elseif (\array_key_exists('UserDefinedText2', $data) && $data['UserDefinedText2'] === null) {
                $object->setUserDefinedText2(null);
            }
            if (\array_key_exists('UserDefinedText3', $data) && $data['UserDefinedText3'] !== null) {
                $object->setUserDefinedText3($data['UserDefinedText3']);
            } elseif (\array_key_exists('UserDefinedText3', $data) && $data['UserDefinedText3'] === null) {
                $object->setUserDefinedText3(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('userDefinedText1') && null !== $object->getUserDefinedText1()) {
                $data['UserDefinedText1'] = $object->getUserDefinedText1();
            }
            if ($object->isInitialized('userDefinedText2') && null !== $object->getUserDefinedText2()) {
                $data['UserDefinedText2'] = $object->getUserDefinedText2();
            }
            if ($object->isInitialized('userDefinedText3') && null !== $object->getUserDefinedText3()) {
                $data['UserDefinedText3'] = $object->getUserDefinedText3();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts' => false];
        }
    }
} else {
    class CegidMtsProductEntityUserDefinedTextsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsProductEntityUserDefinedTexts();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('UserDefinedText1', $data) && $data['UserDefinedText1'] !== null) {
                $object->setUserDefinedText1($data['UserDefinedText1']);
            } elseif (\array_key_exists('UserDefinedText1', $data) && $data['UserDefinedText1'] === null) {
                $object->setUserDefinedText1(null);
            }
            if (\array_key_exists('UserDefinedText2', $data) && $data['UserDefinedText2'] !== null) {
                $object->setUserDefinedText2($data['UserDefinedText2']);
            } elseif (\array_key_exists('UserDefinedText2', $data) && $data['UserDefinedText2'] === null) {
                $object->setUserDefinedText2(null);
            }
            if (\array_key_exists('UserDefinedText3', $data) && $data['UserDefinedText3'] !== null) {
                $object->setUserDefinedText3($data['UserDefinedText3']);
            } elseif (\array_key_exists('UserDefinedText3', $data) && $data['UserDefinedText3'] === null) {
                $object->setUserDefinedText3(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('userDefinedText1') && null !== $object->getUserDefinedText1()) {
                $data['UserDefinedText1'] = $object->getUserDefinedText1();
            }
            if ($object->isInitialized('userDefinedText2') && null !== $object->getUserDefinedText2()) {
                $data['UserDefinedText2'] = $object->getUserDefinedText2();
            }
            if ($object->isInitialized('userDefinedText3') && null !== $object->getUserDefinedText3()) {
                $data['UserDefinedText3'] = $object->getUserDefinedText3();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsProductEntityUserDefinedTexts' => false];
        }
    }
}
