<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReaderNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader();
            if (\array_key_exists('CommissionPercentage', $data) && \is_int($data['CommissionPercentage'])) {
                $data['CommissionPercentage'] = (float) $data['CommissionPercentage'];
            }
            if (\array_key_exists('UserDefinedValue1', $data) && \is_int($data['UserDefinedValue1'])) {
                $data['UserDefinedValue1'] = (float) $data['UserDefinedValue1'];
            }
            if (\array_key_exists('UserDefinedValue2', $data) && \is_int($data['UserDefinedValue2'])) {
                $data['UserDefinedValue2'] = (float) $data['UserDefinedValue2'];
            }
            if (\array_key_exists('UserDefinedValue3', $data) && \is_int($data['UserDefinedValue3'])) {
                $data['UserDefinedValue3'] = (float) $data['UserDefinedValue3'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Type', $data) && $data['Type'] !== null) {
                $object->setType($data['Type']);
            } elseif (\array_key_exists('Type', $data) && $data['Type'] === null) {
                $object->setType(null);
            }
            if (\array_key_exists('TypeLabel', $data) && $data['TypeLabel'] !== null) {
                $object->setTypeLabel($data['TypeLabel']);
            } elseif (\array_key_exists('TypeLabel', $data) && $data['TypeLabel'] === null) {
                $object->setTypeLabel(null);
            }
            if (\array_key_exists('Code', $data) && $data['Code'] !== null) {
                $object->setCode($data['Code']);
            } elseif (\array_key_exists('Code', $data) && $data['Code'] === null) {
                $object->setCode(null);
            }
            if (\array_key_exists('Label', $data) && $data['Label'] !== null) {
                $object->setLabel($data['Label']);
            } elseif (\array_key_exists('Label', $data) && $data['Label'] === null) {
                $object->setLabel(null);
            }
            if (\array_key_exists('FirstName', $data) && $data['FirstName'] !== null) {
                $object->setFirstName($data['FirstName']);
            } elseif (\array_key_exists('FirstName', $data) && $data['FirstName'] === null) {
                $object->setFirstName(null);
            }
            if (\array_key_exists('BusinessCenter', $data) && $data['BusinessCenter'] !== null) {
                $object->setBusinessCenter($data['BusinessCenter']);
            } elseif (\array_key_exists('BusinessCenter', $data) && $data['BusinessCenter'] === null) {
                $object->setBusinessCenter(null);
            }
            if (\array_key_exists('BusinessCenterLabel', $data) && $data['BusinessCenterLabel'] !== null) {
                $object->setBusinessCenterLabel($data['BusinessCenterLabel']);
            } elseif (\array_key_exists('BusinessCenterLabel', $data) && $data['BusinessCenterLabel'] === null) {
                $object->setBusinessCenterLabel(null);
            }
            if (\array_key_exists('Employee', $data) && $data['Employee'] !== null) {
                $object->setEmployee($data['Employee']);
            } elseif (\array_key_exists('Employee', $data) && $data['Employee'] === null) {
                $object->setEmployee(null);
            }
            if (\array_key_exists('EmployeeLabel', $data) && $data['EmployeeLabel'] !== null) {
                $object->setEmployeeLabel($data['EmployeeLabel']);
            } elseif (\array_key_exists('EmployeeLabel', $data) && $data['EmployeeLabel'] === null) {
                $object->setEmployeeLabel(null);
            }
            if (\array_key_exists('CommissionPercentage', $data) && $data['CommissionPercentage'] !== null) {
                $object->setCommissionPercentage($data['CommissionPercentage']);
            } elseif (\array_key_exists('CommissionPercentage', $data) && $data['CommissionPercentage'] === null) {
                $object->setCommissionPercentage(null);
            }
            if (\array_key_exists('AssociatedUser', $data) && $data['AssociatedUser'] !== null) {
                $object->setAssociatedUser($data['AssociatedUser']);
            } elseif (\array_key_exists('AssociatedUser', $data) && $data['AssociatedUser'] === null) {
                $object->setAssociatedUser(null);
            }
            if (\array_key_exists('AssociatedUserLabel', $data) && $data['AssociatedUserLabel'] !== null) {
                $object->setAssociatedUserLabel($data['AssociatedUserLabel']);
            } elseif (\array_key_exists('AssociatedUserLabel', $data) && $data['AssociatedUserLabel'] === null) {
                $object->setAssociatedUserLabel(null);
            }
            if (\array_key_exists('UserDefinedValue1', $data) && $data['UserDefinedValue1'] !== null) {
                $object->setUserDefinedValue1($data['UserDefinedValue1']);
            } elseif (\array_key_exists('UserDefinedValue1', $data) && $data['UserDefinedValue1'] === null) {
                $object->setUserDefinedValue1(null);
            }
            if (\array_key_exists('UserDefinedValue2', $data) && $data['UserDefinedValue2'] !== null) {
                $object->setUserDefinedValue2($data['UserDefinedValue2']);
            } elseif (\array_key_exists('UserDefinedValue2', $data) && $data['UserDefinedValue2'] === null) {
                $object->setUserDefinedValue2(null);
            }
            if (\array_key_exists('UserDefinedValue3', $data) && $data['UserDefinedValue3'] !== null) {
                $object->setUserDefinedValue3($data['UserDefinedValue3']);
            } elseif (\array_key_exists('UserDefinedValue3', $data) && $data['UserDefinedValue3'] === null) {
                $object->setUserDefinedValue3(null);
            }
            if (\array_key_exists('UserDefinedDate1', $data) && $data['UserDefinedDate1'] !== null) {
                $object->setUserDefinedDate1(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate1']));
            } elseif (\array_key_exists('UserDefinedDate1', $data) && $data['UserDefinedDate1'] === null) {
                $object->setUserDefinedDate1(null);
            }
            if (\array_key_exists('UserDefinedDate2', $data) && $data['UserDefinedDate2'] !== null) {
                $object->setUserDefinedDate2(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate2']));
            } elseif (\array_key_exists('UserDefinedDate2', $data) && $data['UserDefinedDate2'] === null) {
                $object->setUserDefinedDate2(null);
            }
            if (\array_key_exists('UserDefinedDate3', $data) && $data['UserDefinedDate3'] !== null) {
                $object->setUserDefinedDate3(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate3']));
            } elseif (\array_key_exists('UserDefinedDate3', $data) && $data['UserDefinedDate3'] === null) {
                $object->setUserDefinedDate3(null);
            }
            if (\array_key_exists('CommercialArea', $data) && $data['CommercialArea'] !== null) {
                $object->setCommercialArea($data['CommercialArea']);
            } elseif (\array_key_exists('CommercialArea', $data) && $data['CommercialArea'] === null) {
                $object->setCommercialArea(null);
            }
            if (\array_key_exists('CommercialAreaLabel', $data) && $data['CommercialAreaLabel'] !== null) {
                $object->setCommercialAreaLabel($data['CommercialAreaLabel']);
            } elseif (\array_key_exists('CommercialAreaLabel', $data) && $data['CommercialAreaLabel'] === null) {
                $object->setCommercialAreaLabel(null);
            }
            if (\array_key_exists('CalculationBasis', $data) && $data['CalculationBasis'] !== null) {
                $object->setCalculationBasis($data['CalculationBasis']);
            } elseif (\array_key_exists('CalculationBasis', $data) && $data['CalculationBasis'] === null) {
                $object->setCalculationBasis(null);
            }
            if (\array_key_exists('CalculationBasisLabel', $data) && $data['CalculationBasisLabel'] !== null) {
                $object->setCalculationBasisLabel($data['CalculationBasisLabel']);
            } elseif (\array_key_exists('CalculationBasisLabel', $data) && $data['CalculationBasisLabel'] === null) {
                $object->setCalculationBasisLabel(null);
            }
            if (\array_key_exists('DocType', $data) && $data['DocType'] !== null) {
                $object->setDocType($data['DocType']);
            } elseif (\array_key_exists('DocType', $data) && $data['DocType'] === null) {
                $object->setDocType(null);
            }
            if (\array_key_exists('ClosedDate', $data) && $data['ClosedDate'] !== null) {
                $object->setClosedDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['ClosedDate']));
            } elseif (\array_key_exists('ClosedDate', $data) && $data['ClosedDate'] === null) {
                $object->setClosedDate(null);
            }
            if (\array_key_exists('Email', $data) && $data['Email'] !== null) {
                $object->setEmail($data['Email']);
            } elseif (\array_key_exists('Email', $data) && $data['Email'] === null) {
                $object->setEmail(null);
            }
            if (\array_key_exists('ThirdPartyCodePrefix', $data) && $data['ThirdPartyCodePrefix'] !== null) {
                $object->setThirdPartyCodePrefix($data['ThirdPartyCodePrefix']);
            } elseif (\array_key_exists('ThirdPartyCodePrefix', $data) && $data['ThirdPartyCodePrefix'] === null) {
                $object->setThirdPartyCodePrefix(null);
            }
            if (\array_key_exists('ServerRank', $data) && $data['ServerRank'] !== null) {
                $object->setServerRank($data['ServerRank']);
            } elseif (\array_key_exists('ServerRank', $data) && $data['ServerRank'] === null) {
                $object->setServerRank(null);
            }
            if (\array_key_exists('IsCommissionPayment', $data) && $data['IsCommissionPayment'] !== null) {
                $object->setIsCommissionPayment($data['IsCommissionPayment']);
            } elseif (\array_key_exists('IsCommissionPayment', $data) && $data['IsCommissionPayment'] === null) {
                $object->setIsCommissionPayment(null);
            }
            if (\array_key_exists('Notepad', $data) && $data['Notepad'] !== null) {
                $object->setNotepad($data['Notepad']);
            } elseif (\array_key_exists('Notepad', $data) && $data['Notepad'] === null) {
                $object->setNotepad(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('type') && null !== $object->getType()) {
                $data['Type'] = $object->getType();
            }
            if ($object->isInitialized('typeLabel') && null !== $object->getTypeLabel()) {
                $data['TypeLabel'] = $object->getTypeLabel();
            }
            $data['Code'] = $object->getCode();
            if ($object->isInitialized('label') && null !== $object->getLabel()) {
                $data['Label'] = $object->getLabel();
            }
            if ($object->isInitialized('firstName') && null !== $object->getFirstName()) {
                $data['FirstName'] = $object->getFirstName();
            }
            if ($object->isInitialized('businessCenter') && null !== $object->getBusinessCenter()) {
                $data['BusinessCenter'] = $object->getBusinessCenter();
            }
            if ($object->isInitialized('businessCenterLabel') && null !== $object->getBusinessCenterLabel()) {
                $data['BusinessCenterLabel'] = $object->getBusinessCenterLabel();
            }
            if ($object->isInitialized('employee') && null !== $object->getEmployee()) {
                $data['Employee'] = $object->getEmployee();
            }
            if ($object->isInitialized('employeeLabel') && null !== $object->getEmployeeLabel()) {
                $data['EmployeeLabel'] = $object->getEmployeeLabel();
            }
            if ($object->isInitialized('commissionPercentage') && null !== $object->getCommissionPercentage()) {
                $data['CommissionPercentage'] = $object->getCommissionPercentage();
            }
            if ($object->isInitialized('associatedUser') && null !== $object->getAssociatedUser()) {
                $data['AssociatedUser'] = $object->getAssociatedUser();
            }
            if ($object->isInitialized('associatedUserLabel') && null !== $object->getAssociatedUserLabel()) {
                $data['AssociatedUserLabel'] = $object->getAssociatedUserLabel();
            }
            if ($object->isInitialized('userDefinedValue1') && null !== $object->getUserDefinedValue1()) {
                $data['UserDefinedValue1'] = $object->getUserDefinedValue1();
            }
            if ($object->isInitialized('userDefinedValue2') && null !== $object->getUserDefinedValue2()) {
                $data['UserDefinedValue2'] = $object->getUserDefinedValue2();
            }
            if ($object->isInitialized('userDefinedValue3') && null !== $object->getUserDefinedValue3()) {
                $data['UserDefinedValue3'] = $object->getUserDefinedValue3();
            }
            if ($object->isInitialized('userDefinedDate1') && null !== $object->getUserDefinedDate1()) {
                $data['UserDefinedDate1'] = $object->getUserDefinedDate1()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('userDefinedDate2') && null !== $object->getUserDefinedDate2()) {
                $data['UserDefinedDate2'] = $object->getUserDefinedDate2()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('userDefinedDate3') && null !== $object->getUserDefinedDate3()) {
                $data['UserDefinedDate3'] = $object->getUserDefinedDate3()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('commercialArea') && null !== $object->getCommercialArea()) {
                $data['CommercialArea'] = $object->getCommercialArea();
            }
            if ($object->isInitialized('commercialAreaLabel') && null !== $object->getCommercialAreaLabel()) {
                $data['CommercialAreaLabel'] = $object->getCommercialAreaLabel();
            }
            if ($object->isInitialized('calculationBasis') && null !== $object->getCalculationBasis()) {
                $data['CalculationBasis'] = $object->getCalculationBasis();
            }
            if ($object->isInitialized('calculationBasisLabel') && null !== $object->getCalculationBasisLabel()) {
                $data['CalculationBasisLabel'] = $object->getCalculationBasisLabel();
            }
            if ($object->isInitialized('docType') && null !== $object->getDocType()) {
                $data['DocType'] = $object->getDocType();
            }
            if ($object->isInitialized('closedDate') && null !== $object->getClosedDate()) {
                $data['ClosedDate'] = $object->getClosedDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('email') && null !== $object->getEmail()) {
                $data['Email'] = $object->getEmail();
            }
            if ($object->isInitialized('thirdPartyCodePrefix') && null !== $object->getThirdPartyCodePrefix()) {
                $data['ThirdPartyCodePrefix'] = $object->getThirdPartyCodePrefix();
            }
            if ($object->isInitialized('serverRank') && null !== $object->getServerRank()) {
                $data['ServerRank'] = $object->getServerRank();
            }
            if ($object->isInitialized('isCommissionPayment') && null !== $object->getIsCommissionPayment()) {
                $data['IsCommissionPayment'] = $object->getIsCommissionPayment();
            }
            if ($object->isInitialized('notepad') && null !== $object->getNotepad()) {
                $data['Notepad'] = $object->getNotepad();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader' => false];
        }
    }
} else {
    class CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReaderNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader();
            if (\array_key_exists('CommissionPercentage', $data) && \is_int($data['CommissionPercentage'])) {
                $data['CommissionPercentage'] = (float) $data['CommissionPercentage'];
            }
            if (\array_key_exists('UserDefinedValue1', $data) && \is_int($data['UserDefinedValue1'])) {
                $data['UserDefinedValue1'] = (float) $data['UserDefinedValue1'];
            }
            if (\array_key_exists('UserDefinedValue2', $data) && \is_int($data['UserDefinedValue2'])) {
                $data['UserDefinedValue2'] = (float) $data['UserDefinedValue2'];
            }
            if (\array_key_exists('UserDefinedValue3', $data) && \is_int($data['UserDefinedValue3'])) {
                $data['UserDefinedValue3'] = (float) $data['UserDefinedValue3'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Type', $data) && $data['Type'] !== null) {
                $object->setType($data['Type']);
            } elseif (\array_key_exists('Type', $data) && $data['Type'] === null) {
                $object->setType(null);
            }
            if (\array_key_exists('TypeLabel', $data) && $data['TypeLabel'] !== null) {
                $object->setTypeLabel($data['TypeLabel']);
            } elseif (\array_key_exists('TypeLabel', $data) && $data['TypeLabel'] === null) {
                $object->setTypeLabel(null);
            }
            if (\array_key_exists('Code', $data) && $data['Code'] !== null) {
                $object->setCode($data['Code']);
            } elseif (\array_key_exists('Code', $data) && $data['Code'] === null) {
                $object->setCode(null);
            }
            if (\array_key_exists('Label', $data) && $data['Label'] !== null) {
                $object->setLabel($data['Label']);
            } elseif (\array_key_exists('Label', $data) && $data['Label'] === null) {
                $object->setLabel(null);
            }
            if (\array_key_exists('FirstName', $data) && $data['FirstName'] !== null) {
                $object->setFirstName($data['FirstName']);
            } elseif (\array_key_exists('FirstName', $data) && $data['FirstName'] === null) {
                $object->setFirstName(null);
            }
            if (\array_key_exists('BusinessCenter', $data) && $data['BusinessCenter'] !== null) {
                $object->setBusinessCenter($data['BusinessCenter']);
            } elseif (\array_key_exists('BusinessCenter', $data) && $data['BusinessCenter'] === null) {
                $object->setBusinessCenter(null);
            }
            if (\array_key_exists('BusinessCenterLabel', $data) && $data['BusinessCenterLabel'] !== null) {
                $object->setBusinessCenterLabel($data['BusinessCenterLabel']);
            } elseif (\array_key_exists('BusinessCenterLabel', $data) && $data['BusinessCenterLabel'] === null) {
                $object->setBusinessCenterLabel(null);
            }
            if (\array_key_exists('Employee', $data) && $data['Employee'] !== null) {
                $object->setEmployee($data['Employee']);
            } elseif (\array_key_exists('Employee', $data) && $data['Employee'] === null) {
                $object->setEmployee(null);
            }
            if (\array_key_exists('EmployeeLabel', $data) && $data['EmployeeLabel'] !== null) {
                $object->setEmployeeLabel($data['EmployeeLabel']);
            } elseif (\array_key_exists('EmployeeLabel', $data) && $data['EmployeeLabel'] === null) {
                $object->setEmployeeLabel(null);
            }
            if (\array_key_exists('CommissionPercentage', $data) && $data['CommissionPercentage'] !== null) {
                $object->setCommissionPercentage($data['CommissionPercentage']);
            } elseif (\array_key_exists('CommissionPercentage', $data) && $data['CommissionPercentage'] === null) {
                $object->setCommissionPercentage(null);
            }
            if (\array_key_exists('AssociatedUser', $data) && $data['AssociatedUser'] !== null) {
                $object->setAssociatedUser($data['AssociatedUser']);
            } elseif (\array_key_exists('AssociatedUser', $data) && $data['AssociatedUser'] === null) {
                $object->setAssociatedUser(null);
            }
            if (\array_key_exists('AssociatedUserLabel', $data) && $data['AssociatedUserLabel'] !== null) {
                $object->setAssociatedUserLabel($data['AssociatedUserLabel']);
            } elseif (\array_key_exists('AssociatedUserLabel', $data) && $data['AssociatedUserLabel'] === null) {
                $object->setAssociatedUserLabel(null);
            }
            if (\array_key_exists('UserDefinedValue1', $data) && $data['UserDefinedValue1'] !== null) {
                $object->setUserDefinedValue1($data['UserDefinedValue1']);
            } elseif (\array_key_exists('UserDefinedValue1', $data) && $data['UserDefinedValue1'] === null) {
                $object->setUserDefinedValue1(null);
            }
            if (\array_key_exists('UserDefinedValue2', $data) && $data['UserDefinedValue2'] !== null) {
                $object->setUserDefinedValue2($data['UserDefinedValue2']);
            } elseif (\array_key_exists('UserDefinedValue2', $data) && $data['UserDefinedValue2'] === null) {
                $object->setUserDefinedValue2(null);
            }
            if (\array_key_exists('UserDefinedValue3', $data) && $data['UserDefinedValue3'] !== null) {
                $object->setUserDefinedValue3($data['UserDefinedValue3']);
            } elseif (\array_key_exists('UserDefinedValue3', $data) && $data['UserDefinedValue3'] === null) {
                $object->setUserDefinedValue3(null);
            }
            if (\array_key_exists('UserDefinedDate1', $data) && $data['UserDefinedDate1'] !== null) {
                $object->setUserDefinedDate1(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate1']));
            } elseif (\array_key_exists('UserDefinedDate1', $data) && $data['UserDefinedDate1'] === null) {
                $object->setUserDefinedDate1(null);
            }
            if (\array_key_exists('UserDefinedDate2', $data) && $data['UserDefinedDate2'] !== null) {
                $object->setUserDefinedDate2(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate2']));
            } elseif (\array_key_exists('UserDefinedDate2', $data) && $data['UserDefinedDate2'] === null) {
                $object->setUserDefinedDate2(null);
            }
            if (\array_key_exists('UserDefinedDate3', $data) && $data['UserDefinedDate3'] !== null) {
                $object->setUserDefinedDate3(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['UserDefinedDate3']));
            } elseif (\array_key_exists('UserDefinedDate3', $data) && $data['UserDefinedDate3'] === null) {
                $object->setUserDefinedDate3(null);
            }
            if (\array_key_exists('CommercialArea', $data) && $data['CommercialArea'] !== null) {
                $object->setCommercialArea($data['CommercialArea']);
            } elseif (\array_key_exists('CommercialArea', $data) && $data['CommercialArea'] === null) {
                $object->setCommercialArea(null);
            }
            if (\array_key_exists('CommercialAreaLabel', $data) && $data['CommercialAreaLabel'] !== null) {
                $object->setCommercialAreaLabel($data['CommercialAreaLabel']);
            } elseif (\array_key_exists('CommercialAreaLabel', $data) && $data['CommercialAreaLabel'] === null) {
                $object->setCommercialAreaLabel(null);
            }
            if (\array_key_exists('CalculationBasis', $data) && $data['CalculationBasis'] !== null) {
                $object->setCalculationBasis($data['CalculationBasis']);
            } elseif (\array_key_exists('CalculationBasis', $data) && $data['CalculationBasis'] === null) {
                $object->setCalculationBasis(null);
            }
            if (\array_key_exists('CalculationBasisLabel', $data) && $data['CalculationBasisLabel'] !== null) {
                $object->setCalculationBasisLabel($data['CalculationBasisLabel']);
            } elseif (\array_key_exists('CalculationBasisLabel', $data) && $data['CalculationBasisLabel'] === null) {
                $object->setCalculationBasisLabel(null);
            }
            if (\array_key_exists('DocType', $data) && $data['DocType'] !== null) {
                $object->setDocType($data['DocType']);
            } elseif (\array_key_exists('DocType', $data) && $data['DocType'] === null) {
                $object->setDocType(null);
            }
            if (\array_key_exists('ClosedDate', $data) && $data['ClosedDate'] !== null) {
                $object->setClosedDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['ClosedDate']));
            } elseif (\array_key_exists('ClosedDate', $data) && $data['ClosedDate'] === null) {
                $object->setClosedDate(null);
            }
            if (\array_key_exists('Email', $data) && $data['Email'] !== null) {
                $object->setEmail($data['Email']);
            } elseif (\array_key_exists('Email', $data) && $data['Email'] === null) {
                $object->setEmail(null);
            }
            if (\array_key_exists('ThirdPartyCodePrefix', $data) && $data['ThirdPartyCodePrefix'] !== null) {
                $object->setThirdPartyCodePrefix($data['ThirdPartyCodePrefix']);
            } elseif (\array_key_exists('ThirdPartyCodePrefix', $data) && $data['ThirdPartyCodePrefix'] === null) {
                $object->setThirdPartyCodePrefix(null);
            }
            if (\array_key_exists('ServerRank', $data) && $data['ServerRank'] !== null) {
                $object->setServerRank($data['ServerRank']);
            } elseif (\array_key_exists('ServerRank', $data) && $data['ServerRank'] === null) {
                $object->setServerRank(null);
            }
            if (\array_key_exists('IsCommissionPayment', $data) && $data['IsCommissionPayment'] !== null) {
                $object->setIsCommissionPayment($data['IsCommissionPayment']);
            } elseif (\array_key_exists('IsCommissionPayment', $data) && $data['IsCommissionPayment'] === null) {
                $object->setIsCommissionPayment(null);
            }
            if (\array_key_exists('Notepad', $data) && $data['Notepad'] !== null) {
                $object->setNotepad($data['Notepad']);
            } elseif (\array_key_exists('Notepad', $data) && $data['Notepad'] === null) {
                $object->setNotepad(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('type') && null !== $object->getType()) {
                $data['Type'] = $object->getType();
            }
            if ($object->isInitialized('typeLabel') && null !== $object->getTypeLabel()) {
                $data['TypeLabel'] = $object->getTypeLabel();
            }
            $data['Code'] = $object->getCode();
            if ($object->isInitialized('label') && null !== $object->getLabel()) {
                $data['Label'] = $object->getLabel();
            }
            if ($object->isInitialized('firstName') && null !== $object->getFirstName()) {
                $data['FirstName'] = $object->getFirstName();
            }
            if ($object->isInitialized('businessCenter') && null !== $object->getBusinessCenter()) {
                $data['BusinessCenter'] = $object->getBusinessCenter();
            }
            if ($object->isInitialized('businessCenterLabel') && null !== $object->getBusinessCenterLabel()) {
                $data['BusinessCenterLabel'] = $object->getBusinessCenterLabel();
            }
            if ($object->isInitialized('employee') && null !== $object->getEmployee()) {
                $data['Employee'] = $object->getEmployee();
            }
            if ($object->isInitialized('employeeLabel') && null !== $object->getEmployeeLabel()) {
                $data['EmployeeLabel'] = $object->getEmployeeLabel();
            }
            if ($object->isInitialized('commissionPercentage') && null !== $object->getCommissionPercentage()) {
                $data['CommissionPercentage'] = $object->getCommissionPercentage();
            }
            if ($object->isInitialized('associatedUser') && null !== $object->getAssociatedUser()) {
                $data['AssociatedUser'] = $object->getAssociatedUser();
            }
            if ($object->isInitialized('associatedUserLabel') && null !== $object->getAssociatedUserLabel()) {
                $data['AssociatedUserLabel'] = $object->getAssociatedUserLabel();
            }
            if ($object->isInitialized('userDefinedValue1') && null !== $object->getUserDefinedValue1()) {
                $data['UserDefinedValue1'] = $object->getUserDefinedValue1();
            }
            if ($object->isInitialized('userDefinedValue2') && null !== $object->getUserDefinedValue2()) {
                $data['UserDefinedValue2'] = $object->getUserDefinedValue2();
            }
            if ($object->isInitialized('userDefinedValue3') && null !== $object->getUserDefinedValue3()) {
                $data['UserDefinedValue3'] = $object->getUserDefinedValue3();
            }
            if ($object->isInitialized('userDefinedDate1') && null !== $object->getUserDefinedDate1()) {
                $data['UserDefinedDate1'] = $object->getUserDefinedDate1()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('userDefinedDate2') && null !== $object->getUserDefinedDate2()) {
                $data['UserDefinedDate2'] = $object->getUserDefinedDate2()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('userDefinedDate3') && null !== $object->getUserDefinedDate3()) {
                $data['UserDefinedDate3'] = $object->getUserDefinedDate3()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('commercialArea') && null !== $object->getCommercialArea()) {
                $data['CommercialArea'] = $object->getCommercialArea();
            }
            if ($object->isInitialized('commercialAreaLabel') && null !== $object->getCommercialAreaLabel()) {
                $data['CommercialAreaLabel'] = $object->getCommercialAreaLabel();
            }
            if ($object->isInitialized('calculationBasis') && null !== $object->getCalculationBasis()) {
                $data['CalculationBasis'] = $object->getCalculationBasis();
            }
            if ($object->isInitialized('calculationBasisLabel') && null !== $object->getCalculationBasisLabel()) {
                $data['CalculationBasisLabel'] = $object->getCalculationBasisLabel();
            }
            if ($object->isInitialized('docType') && null !== $object->getDocType()) {
                $data['DocType'] = $object->getDocType();
            }
            if ($object->isInitialized('closedDate') && null !== $object->getClosedDate()) {
                $data['ClosedDate'] = $object->getClosedDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('email') && null !== $object->getEmail()) {
                $data['Email'] = $object->getEmail();
            }
            if ($object->isInitialized('thirdPartyCodePrefix') && null !== $object->getThirdPartyCodePrefix()) {
                $data['ThirdPartyCodePrefix'] = $object->getThirdPartyCodePrefix();
            }
            if ($object->isInitialized('serverRank') && null !== $object->getServerRank()) {
                $data['ServerRank'] = $object->getServerRank();
            }
            if ($object->isInitialized('isCommissionPayment') && null !== $object->getIsCommissionPayment()) {
                $data['IsCommissionPayment'] = $object->getIsCommissionPayment();
            }
            if ($object->isInitialized('notepad') && null !== $object->getNotepad()) {
                $data['Notepad'] = $object->getNotepad();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader' => false];
        }
    }
}
