<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsActivityActivityKeyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsActivityActivityKey';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsActivityActivityKey';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsActivityActivityKey();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('ActivityType', $data) && $data['ActivityType'] !== null) {
                $object->setActivityType($data['ActivityType']);
            } elseif (\array_key_exists('ActivityType', $data) && $data['ActivityType'] === null) {
                $object->setActivityType(null);
            }
            if (\array_key_exists('Project', $data) && $data['Project'] !== null) {
                $object->setProject($data['Project']);
            } elseif (\array_key_exists('Project', $data) && $data['Project'] === null) {
                $object->setProject(null);
            }
            if (\array_key_exists('SingleLineNumber', $data) && $data['SingleLineNumber'] !== null) {
                $object->setSingleLineNumber($data['SingleLineNumber']);
            } elseif (\array_key_exists('SingleLineNumber', $data) && $data['SingleLineNumber'] === null) {
                $object->setSingleLineNumber(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('activityType') && null !== $object->getActivityType()) {
                $data['ActivityType'] = $object->getActivityType();
            }
            if ($object->isInitialized('project') && null !== $object->getProject()) {
                $data['Project'] = $object->getProject();
            }
            if ($object->isInitialized('singleLineNumber') && null !== $object->getSingleLineNumber()) {
                $data['SingleLineNumber'] = $object->getSingleLineNumber();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsActivityActivityKey' => false];
        }
    }
} else {
    class CegidMtsActivityActivityKeyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsActivityActivityKey';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsActivityActivityKey';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsActivityActivityKey();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('ActivityType', $data) && $data['ActivityType'] !== null) {
                $object->setActivityType($data['ActivityType']);
            } elseif (\array_key_exists('ActivityType', $data) && $data['ActivityType'] === null) {
                $object->setActivityType(null);
            }
            if (\array_key_exists('Project', $data) && $data['Project'] !== null) {
                $object->setProject($data['Project']);
            } elseif (\array_key_exists('Project', $data) && $data['Project'] === null) {
                $object->setProject(null);
            }
            if (\array_key_exists('SingleLineNumber', $data) && $data['SingleLineNumber'] !== null) {
                $object->setSingleLineNumber($data['SingleLineNumber']);
            } elseif (\array_key_exists('SingleLineNumber', $data) && $data['SingleLineNumber'] === null) {
                $object->setSingleLineNumber(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('activityType') && null !== $object->getActivityType()) {
                $data['ActivityType'] = $object->getActivityType();
            }
            if ($object->isInitialized('project') && null !== $object->getProject()) {
                $data['Project'] = $object->getProject();
            }
            if ($object->isInitialized('singleLineNumber') && null !== $object->getSingleLineNumber()) {
                $data['SingleLineNumber'] = $object->getSingleLineNumber();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsActivityActivityKey' => false];
        }
    }
}
