<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsAddressesV1CustomerAddressReplyKeysDataNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsAddressesV1CustomerAddressReplyKeysData();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('AddressType', $data) && $data['AddressType'] !== null) {
                $object->setAddressType($data['AddressType']);
            } elseif (\array_key_exists('AddressType', $data) && $data['AddressType'] === null) {
                $object->setAddressType(null);
            }
            if (\array_key_exists('InternalAddressNumber', $data) && $data['InternalAddressNumber'] !== null) {
                $object->setInternalAddressNumber($data['InternalAddressNumber']);
            } elseif (\array_key_exists('InternalAddressNumber', $data) && $data['InternalAddressNumber'] === null) {
                $object->setInternalAddressNumber(null);
            }
            if (\array_key_exists('CustomerCode', $data) && $data['CustomerCode'] !== null) {
                $object->setCustomerCode($data['CustomerCode']);
            } elseif (\array_key_exists('CustomerCode', $data) && $data['CustomerCode'] === null) {
                $object->setCustomerCode(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('addressType') && null !== $object->getAddressType()) {
                $data['AddressType'] = $object->getAddressType();
            }
            if ($object->isInitialized('internalAddressNumber') && null !== $object->getInternalAddressNumber()) {
                $data['InternalAddressNumber'] = $object->getInternalAddressNumber();
            }
            if ($object->isInitialized('customerCode') && null !== $object->getCustomerCode()) {
                $data['CustomerCode'] = $object->getCustomerCode();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData' => false];
        }
    }
} else {
    class CegidMtsAddressesV1CustomerAddressReplyKeysDataNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsAddressesV1CustomerAddressReplyKeysData();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('AddressType', $data) && $data['AddressType'] !== null) {
                $object->setAddressType($data['AddressType']);
            } elseif (\array_key_exists('AddressType', $data) && $data['AddressType'] === null) {
                $object->setAddressType(null);
            }
            if (\array_key_exists('InternalAddressNumber', $data) && $data['InternalAddressNumber'] !== null) {
                $object->setInternalAddressNumber($data['InternalAddressNumber']);
            } elseif (\array_key_exists('InternalAddressNumber', $data) && $data['InternalAddressNumber'] === null) {
                $object->setInternalAddressNumber(null);
            }
            if (\array_key_exists('CustomerCode', $data) && $data['CustomerCode'] !== null) {
                $object->setCustomerCode($data['CustomerCode']);
            } elseif (\array_key_exists('CustomerCode', $data) && $data['CustomerCode'] === null) {
                $object->setCustomerCode(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('addressType') && null !== $object->getAddressType()) {
                $data['AddressType'] = $object->getAddressType();
            }
            if ($object->isInitialized('internalAddressNumber') && null !== $object->getInternalAddressNumber()) {
                $data['InternalAddressNumber'] = $object->getInternalAddressNumber();
            }
            if ($object->isInitialized('customerCode') && null !== $object->getCustomerCode()) {
                $data['CustomerCode'] = $object->getCustomerCode();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsAddressesV1CustomerAddressReplyKeysData' => false];
        }
    }
}
