<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReaderNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader();
            if (\array_key_exists('SubmittedAmountTaxIncluding', $data) && \is_int($data['SubmittedAmountTaxIncluding'])) {
                $data['SubmittedAmountTaxIncluding'] = (float) $data['SubmittedAmountTaxIncluding'];
            }
            if (\array_key_exists('ApprovalAmountTaxIncluding', $data) && \is_int($data['ApprovalAmountTaxIncluding'])) {
                $data['ApprovalAmountTaxIncluding'] = (float) $data['ApprovalAmountTaxIncluding'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Id', $data) && $data['Id'] !== null) {
                $object->setId($data['Id']);
            } elseif (\array_key_exists('Id', $data) && $data['Id'] === null) {
                $object->setId(null);
            }
            if (\array_key_exists('Resource', $data) && $data['Resource'] !== null) {
                $object->setResource($data['Resource']);
            } elseif (\array_key_exists('Resource', $data) && $data['Resource'] === null) {
                $object->setResource(null);
            }
            if (\array_key_exists('ResourceLabel', $data) && $data['ResourceLabel'] !== null) {
                $object->setResourceLabel($data['ResourceLabel']);
            } elseif (\array_key_exists('ResourceLabel', $data) && $data['ResourceLabel'] === null) {
                $object->setResourceLabel(null);
            }
            if (\array_key_exists('PeriodStartDate', $data) && $data['PeriodStartDate'] !== null) {
                $object->setPeriodStartDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['PeriodStartDate']));
            } elseif (\array_key_exists('PeriodStartDate', $data) && $data['PeriodStartDate'] === null) {
                $object->setPeriodStartDate(null);
            }
            if (\array_key_exists('PeriodEndDate', $data) && $data['PeriodEndDate'] !== null) {
                $object->setPeriodEndDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['PeriodEndDate']));
            } elseif (\array_key_exists('PeriodEndDate', $data) && $data['PeriodEndDate'] === null) {
                $object->setPeriodEndDate(null);
            }
            if (\array_key_exists('SubmittedDate', $data) && $data['SubmittedDate'] !== null) {
                $object->setSubmittedDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['SubmittedDate']));
            } elseif (\array_key_exists('SubmittedDate', $data) && $data['SubmittedDate'] === null) {
                $object->setSubmittedDate(null);
            }
            if (\array_key_exists('State', $data) && $data['State'] !== null) {
                $object->setState($data['State']);
            } elseif (\array_key_exists('State', $data) && $data['State'] === null) {
                $object->setState(null);
            }
            if (\array_key_exists('StateLabel', $data) && $data['StateLabel'] !== null) {
                $object->setStateLabel($data['StateLabel']);
            } elseif (\array_key_exists('StateLabel', $data) && $data['StateLabel'] === null) {
                $object->setStateLabel(null);
            }
            if (\array_key_exists('SubmittedAmountTaxIncluding', $data) && $data['SubmittedAmountTaxIncluding'] !== null) {
                $object->setSubmittedAmountTaxIncluding($data['SubmittedAmountTaxIncluding']);
            } elseif (\array_key_exists('SubmittedAmountTaxIncluding', $data) && $data['SubmittedAmountTaxIncluding'] === null) {
                $object->setSubmittedAmountTaxIncluding(null);
            }
            if (\array_key_exists('ApprovalAmountTaxIncluding', $data) && $data['ApprovalAmountTaxIncluding'] !== null) {
                $object->setApprovalAmountTaxIncluding($data['ApprovalAmountTaxIncluding']);
            } elseif (\array_key_exists('ApprovalAmountTaxIncluding', $data) && $data['ApprovalAmountTaxIncluding'] === null) {
                $object->setApprovalAmountTaxIncluding(null);
            }
            if (\array_key_exists('AccountingReference', $data) && $data['AccountingReference'] !== null) {
                $object->setAccountingReference($data['AccountingReference']);
            } elseif (\array_key_exists('AccountingReference', $data) && $data['AccountingReference'] === null) {
                $object->setAccountingReference(null);
            }
            if (\array_key_exists('Comments', $data) && $data['Comments'] !== null) {
                $object->setComments($data['Comments']);
            } elseif (\array_key_exists('Comments', $data) && $data['Comments'] === null) {
                $object->setComments(null);
            }
            if (\array_key_exists('LastActionDate', $data) && $data['LastActionDate'] !== null) {
                $object->setLastActionDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['LastActionDate']));
            } elseif (\array_key_exists('LastActionDate', $data) && $data['LastActionDate'] === null) {
                $object->setLastActionDate(null);
            }
            if (\array_key_exists('LastActionResource', $data) && $data['LastActionResource'] !== null) {
                $object->setLastActionResource($data['LastActionResource']);
            } elseif (\array_key_exists('LastActionResource', $data) && $data['LastActionResource'] === null) {
                $object->setLastActionResource(null);
            }
            if (\array_key_exists('LastActionResourceLabel', $data) && $data['LastActionResourceLabel'] !== null) {
                $object->setLastActionResourceLabel($data['LastActionResourceLabel']);
            } elseif (\array_key_exists('LastActionResourceLabel', $data) && $data['LastActionResourceLabel'] === null) {
                $object->setLastActionResourceLabel(null);
            }
            if (\array_key_exists('CreationDate', $data) && $data['CreationDate'] !== null) {
                $object->setCreationDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['CreationDate']));
            } elseif (\array_key_exists('CreationDate', $data) && $data['CreationDate'] === null) {
                $object->setCreationDate(null);
            }
            if (\array_key_exists('ModificationDate', $data) && $data['ModificationDate'] !== null) {
                $object->setModificationDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['ModificationDate']));
            } elseif (\array_key_exists('ModificationDate', $data) && $data['ModificationDate'] === null) {
                $object->setModificationDate(null);
            }
            if (\array_key_exists('CreatedBy', $data) && $data['CreatedBy'] !== null) {
                $object->setCreatedBy($data['CreatedBy']);
            } elseif (\array_key_exists('CreatedBy', $data) && $data['CreatedBy'] === null) {
                $object->setCreatedBy(null);
            }
            if (\array_key_exists('CreatedByLabel', $data) && $data['CreatedByLabel'] !== null) {
                $object->setCreatedByLabel($data['CreatedByLabel']);
            } elseif (\array_key_exists('CreatedByLabel', $data) && $data['CreatedByLabel'] === null) {
                $object->setCreatedByLabel(null);
            }
            if (\array_key_exists('ModifiedBy', $data) && $data['ModifiedBy'] !== null) {
                $object->setModifiedBy($data['ModifiedBy']);
            } elseif (\array_key_exists('ModifiedBy', $data) && $data['ModifiedBy'] === null) {
                $object->setModifiedBy(null);
            }
            if (\array_key_exists('ModifiedByLabel', $data) && $data['ModifiedByLabel'] !== null) {
                $object->setModifiedByLabel($data['ModifiedByLabel']);
            } elseif (\array_key_exists('ModifiedByLabel', $data) && $data['ModifiedByLabel'] === null) {
                $object->setModifiedByLabel(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['Id'] = $object->getId();
            }
            if ($object->isInitialized('resource') && null !== $object->getResource()) {
                $data['Resource'] = $object->getResource();
            }
            if ($object->isInitialized('resourceLabel') && null !== $object->getResourceLabel()) {
                $data['ResourceLabel'] = $object->getResourceLabel();
            }
            if ($object->isInitialized('periodStartDate') && null !== $object->getPeriodStartDate()) {
                $data['PeriodStartDate'] = $object->getPeriodStartDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('periodEndDate') && null !== $object->getPeriodEndDate()) {
                $data['PeriodEndDate'] = $object->getPeriodEndDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('submittedDate') && null !== $object->getSubmittedDate()) {
                $data['SubmittedDate'] = $object->getSubmittedDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('state') && null !== $object->getState()) {
                $data['State'] = $object->getState();
            }
            if ($object->isInitialized('stateLabel') && null !== $object->getStateLabel()) {
                $data['StateLabel'] = $object->getStateLabel();
            }
            if ($object->isInitialized('submittedAmountTaxIncluding') && null !== $object->getSubmittedAmountTaxIncluding()) {
                $data['SubmittedAmountTaxIncluding'] = $object->getSubmittedAmountTaxIncluding();
            }
            if ($object->isInitialized('approvalAmountTaxIncluding') && null !== $object->getApprovalAmountTaxIncluding()) {
                $data['ApprovalAmountTaxIncluding'] = $object->getApprovalAmountTaxIncluding();
            }
            if ($object->isInitialized('accountingReference') && null !== $object->getAccountingReference()) {
                $data['AccountingReference'] = $object->getAccountingReference();
            }
            if ($object->isInitialized('comments') && null !== $object->getComments()) {
                $data['Comments'] = $object->getComments();
            }
            if ($object->isInitialized('lastActionDate') && null !== $object->getLastActionDate()) {
                $data['LastActionDate'] = $object->getLastActionDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('lastActionResource') && null !== $object->getLastActionResource()) {
                $data['LastActionResource'] = $object->getLastActionResource();
            }
            if ($object->isInitialized('lastActionResourceLabel') && null !== $object->getLastActionResourceLabel()) {
                $data['LastActionResourceLabel'] = $object->getLastActionResourceLabel();
            }
            if ($object->isInitialized('creationDate') && null !== $object->getCreationDate()) {
                $data['CreationDate'] = $object->getCreationDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('modificationDate') && null !== $object->getModificationDate()) {
                $data['ModificationDate'] = $object->getModificationDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('createdBy') && null !== $object->getCreatedBy()) {
                $data['CreatedBy'] = $object->getCreatedBy();
            }
            if ($object->isInitialized('createdByLabel') && null !== $object->getCreatedByLabel()) {
                $data['CreatedByLabel'] = $object->getCreatedByLabel();
            }
            if ($object->isInitialized('modifiedBy') && null !== $object->getModifiedBy()) {
                $data['ModifiedBy'] = $object->getModifiedBy();
            }
            if ($object->isInitialized('modifiedByLabel') && null !== $object->getModifiedByLabel()) {
                $data['ModifiedByLabel'] = $object->getModifiedByLabel();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader' => false];
        }
    }
} else {
    class CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReaderNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader();
            if (\array_key_exists('SubmittedAmountTaxIncluding', $data) && \is_int($data['SubmittedAmountTaxIncluding'])) {
                $data['SubmittedAmountTaxIncluding'] = (float) $data['SubmittedAmountTaxIncluding'];
            }
            if (\array_key_exists('ApprovalAmountTaxIncluding', $data) && \is_int($data['ApprovalAmountTaxIncluding'])) {
                $data['ApprovalAmountTaxIncluding'] = (float) $data['ApprovalAmountTaxIncluding'];
            }
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Id', $data) && $data['Id'] !== null) {
                $object->setId($data['Id']);
            } elseif (\array_key_exists('Id', $data) && $data['Id'] === null) {
                $object->setId(null);
            }
            if (\array_key_exists('Resource', $data) && $data['Resource'] !== null) {
                $object->setResource($data['Resource']);
            } elseif (\array_key_exists('Resource', $data) && $data['Resource'] === null) {
                $object->setResource(null);
            }
            if (\array_key_exists('ResourceLabel', $data) && $data['ResourceLabel'] !== null) {
                $object->setResourceLabel($data['ResourceLabel']);
            } elseif (\array_key_exists('ResourceLabel', $data) && $data['ResourceLabel'] === null) {
                $object->setResourceLabel(null);
            }
            if (\array_key_exists('PeriodStartDate', $data) && $data['PeriodStartDate'] !== null) {
                $object->setPeriodStartDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['PeriodStartDate']));
            } elseif (\array_key_exists('PeriodStartDate', $data) && $data['PeriodStartDate'] === null) {
                $object->setPeriodStartDate(null);
            }
            if (\array_key_exists('PeriodEndDate', $data) && $data['PeriodEndDate'] !== null) {
                $object->setPeriodEndDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['PeriodEndDate']));
            } elseif (\array_key_exists('PeriodEndDate', $data) && $data['PeriodEndDate'] === null) {
                $object->setPeriodEndDate(null);
            }
            if (\array_key_exists('SubmittedDate', $data) && $data['SubmittedDate'] !== null) {
                $object->setSubmittedDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['SubmittedDate']));
            } elseif (\array_key_exists('SubmittedDate', $data) && $data['SubmittedDate'] === null) {
                $object->setSubmittedDate(null);
            }
            if (\array_key_exists('State', $data) && $data['State'] !== null) {
                $object->setState($data['State']);
            } elseif (\array_key_exists('State', $data) && $data['State'] === null) {
                $object->setState(null);
            }
            if (\array_key_exists('StateLabel', $data) && $data['StateLabel'] !== null) {
                $object->setStateLabel($data['StateLabel']);
            } elseif (\array_key_exists('StateLabel', $data) && $data['StateLabel'] === null) {
                $object->setStateLabel(null);
            }
            if (\array_key_exists('SubmittedAmountTaxIncluding', $data) && $data['SubmittedAmountTaxIncluding'] !== null) {
                $object->setSubmittedAmountTaxIncluding($data['SubmittedAmountTaxIncluding']);
            } elseif (\array_key_exists('SubmittedAmountTaxIncluding', $data) && $data['SubmittedAmountTaxIncluding'] === null) {
                $object->setSubmittedAmountTaxIncluding(null);
            }
            if (\array_key_exists('ApprovalAmountTaxIncluding', $data) && $data['ApprovalAmountTaxIncluding'] !== null) {
                $object->setApprovalAmountTaxIncluding($data['ApprovalAmountTaxIncluding']);
            } elseif (\array_key_exists('ApprovalAmountTaxIncluding', $data) && $data['ApprovalAmountTaxIncluding'] === null) {
                $object->setApprovalAmountTaxIncluding(null);
            }
            if (\array_key_exists('AccountingReference', $data) && $data['AccountingReference'] !== null) {
                $object->setAccountingReference($data['AccountingReference']);
            } elseif (\array_key_exists('AccountingReference', $data) && $data['AccountingReference'] === null) {
                $object->setAccountingReference(null);
            }
            if (\array_key_exists('Comments', $data) && $data['Comments'] !== null) {
                $object->setComments($data['Comments']);
            } elseif (\array_key_exists('Comments', $data) && $data['Comments'] === null) {
                $object->setComments(null);
            }
            if (\array_key_exists('LastActionDate', $data) && $data['LastActionDate'] !== null) {
                $object->setLastActionDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['LastActionDate']));
            } elseif (\array_key_exists('LastActionDate', $data) && $data['LastActionDate'] === null) {
                $object->setLastActionDate(null);
            }
            if (\array_key_exists('LastActionResource', $data) && $data['LastActionResource'] !== null) {
                $object->setLastActionResource($data['LastActionResource']);
            } elseif (\array_key_exists('LastActionResource', $data) && $data['LastActionResource'] === null) {
                $object->setLastActionResource(null);
            }
            if (\array_key_exists('LastActionResourceLabel', $data) && $data['LastActionResourceLabel'] !== null) {
                $object->setLastActionResourceLabel($data['LastActionResourceLabel']);
            } elseif (\array_key_exists('LastActionResourceLabel', $data) && $data['LastActionResourceLabel'] === null) {
                $object->setLastActionResourceLabel(null);
            }
            if (\array_key_exists('CreationDate', $data) && $data['CreationDate'] !== null) {
                $object->setCreationDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['CreationDate']));
            } elseif (\array_key_exists('CreationDate', $data) && $data['CreationDate'] === null) {
                $object->setCreationDate(null);
            }
            if (\array_key_exists('ModificationDate', $data) && $data['ModificationDate'] !== null) {
                $object->setModificationDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['ModificationDate']));
            } elseif (\array_key_exists('ModificationDate', $data) && $data['ModificationDate'] === null) {
                $object->setModificationDate(null);
            }
            if (\array_key_exists('CreatedBy', $data) && $data['CreatedBy'] !== null) {
                $object->setCreatedBy($data['CreatedBy']);
            } elseif (\array_key_exists('CreatedBy', $data) && $data['CreatedBy'] === null) {
                $object->setCreatedBy(null);
            }
            if (\array_key_exists('CreatedByLabel', $data) && $data['CreatedByLabel'] !== null) {
                $object->setCreatedByLabel($data['CreatedByLabel']);
            } elseif (\array_key_exists('CreatedByLabel', $data) && $data['CreatedByLabel'] === null) {
                $object->setCreatedByLabel(null);
            }
            if (\array_key_exists('ModifiedBy', $data) && $data['ModifiedBy'] !== null) {
                $object->setModifiedBy($data['ModifiedBy']);
            } elseif (\array_key_exists('ModifiedBy', $data) && $data['ModifiedBy'] === null) {
                $object->setModifiedBy(null);
            }
            if (\array_key_exists('ModifiedByLabel', $data) && $data['ModifiedByLabel'] !== null) {
                $object->setModifiedByLabel($data['ModifiedByLabel']);
            } elseif (\array_key_exists('ModifiedByLabel', $data) && $data['ModifiedByLabel'] === null) {
                $object->setModifiedByLabel(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('id') && null !== $object->getId()) {
                $data['Id'] = $object->getId();
            }
            if ($object->isInitialized('resource') && null !== $object->getResource()) {
                $data['Resource'] = $object->getResource();
            }
            if ($object->isInitialized('resourceLabel') && null !== $object->getResourceLabel()) {
                $data['ResourceLabel'] = $object->getResourceLabel();
            }
            if ($object->isInitialized('periodStartDate') && null !== $object->getPeriodStartDate()) {
                $data['PeriodStartDate'] = $object->getPeriodStartDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('periodEndDate') && null !== $object->getPeriodEndDate()) {
                $data['PeriodEndDate'] = $object->getPeriodEndDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('submittedDate') && null !== $object->getSubmittedDate()) {
                $data['SubmittedDate'] = $object->getSubmittedDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('state') && null !== $object->getState()) {
                $data['State'] = $object->getState();
            }
            if ($object->isInitialized('stateLabel') && null !== $object->getStateLabel()) {
                $data['StateLabel'] = $object->getStateLabel();
            }
            if ($object->isInitialized('submittedAmountTaxIncluding') && null !== $object->getSubmittedAmountTaxIncluding()) {
                $data['SubmittedAmountTaxIncluding'] = $object->getSubmittedAmountTaxIncluding();
            }
            if ($object->isInitialized('approvalAmountTaxIncluding') && null !== $object->getApprovalAmountTaxIncluding()) {
                $data['ApprovalAmountTaxIncluding'] = $object->getApprovalAmountTaxIncluding();
            }
            if ($object->isInitialized('accountingReference') && null !== $object->getAccountingReference()) {
                $data['AccountingReference'] = $object->getAccountingReference();
            }
            if ($object->isInitialized('comments') && null !== $object->getComments()) {
                $data['Comments'] = $object->getComments();
            }
            if ($object->isInitialized('lastActionDate') && null !== $object->getLastActionDate()) {
                $data['LastActionDate'] = $object->getLastActionDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('lastActionResource') && null !== $object->getLastActionResource()) {
                $data['LastActionResource'] = $object->getLastActionResource();
            }
            if ($object->isInitialized('lastActionResourceLabel') && null !== $object->getLastActionResourceLabel()) {
                $data['LastActionResourceLabel'] = $object->getLastActionResourceLabel();
            }
            if ($object->isInitialized('creationDate') && null !== $object->getCreationDate()) {
                $data['CreationDate'] = $object->getCreationDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('modificationDate') && null !== $object->getModificationDate()) {
                $data['ModificationDate'] = $object->getModificationDate()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('createdBy') && null !== $object->getCreatedBy()) {
                $data['CreatedBy'] = $object->getCreatedBy();
            }
            if ($object->isInitialized('createdByLabel') && null !== $object->getCreatedByLabel()) {
                $data['CreatedByLabel'] = $object->getCreatedByLabel();
            }
            if ($object->isInitialized('modifiedBy') && null !== $object->getModifiedBy()) {
                $data['ModifiedBy'] = $object->getModifiedBy();
            }
            if ($object->isInitialized('modifiedByLabel') && null !== $object->getModifiedByLabel()) {
                $data['ModifiedByLabel'] = $object->getModifiedByLabel();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsActivityExpensesSheetExpensesSheetBaseDtoReader' => false];
        }
    }
}
