<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsStockModelsChangeLocationParametersNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsStockModelsChangeLocationParameters();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Warehouse', $data) && $data['Warehouse'] !== null) {
                $object->setWarehouse($data['Warehouse']);
            } elseif (\array_key_exists('Warehouse', $data) && $data['Warehouse'] === null) {
                $object->setWarehouse(null);
            }
            if (\array_key_exists('Movements', $data) && $data['Movements'] !== null) {
                $values = [];
                foreach ($data['Movements'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationRowParameters', 'json', $context);
                }
                $object->setMovements($values);
            } elseif (\array_key_exists('Movements', $data) && $data['Movements'] === null) {
                $object->setMovements(null);
            }
            if (\array_key_exists('DestinationLocation', $data) && $data['DestinationLocation'] !== null) {
                $object->setDestinationLocation($data['DestinationLocation']);
            } elseif (\array_key_exists('DestinationLocation', $data) && $data['DestinationLocation'] === null) {
                $object->setDestinationLocation(null);
            }
            if (\array_key_exists('DestinationAvailabilityStatus', $data) && $data['DestinationAvailabilityStatus'] !== null) {
                $object->setDestinationAvailabilityStatus($data['DestinationAvailabilityStatus']);
            } elseif (\array_key_exists('DestinationAvailabilityStatus', $data) && $data['DestinationAvailabilityStatus'] === null) {
                $object->setDestinationAvailabilityStatus(null);
            }
            if (\array_key_exists('DestinationFluxStatus', $data) && $data['DestinationFluxStatus'] !== null) {
                $object->setDestinationFluxStatus($data['DestinationFluxStatus']);
            } elseif (\array_key_exists('DestinationFluxStatus', $data) && $data['DestinationFluxStatus'] === null) {
                $object->setDestinationFluxStatus(null);
            }
            if (\array_key_exists('DateMovement', $data) && $data['DateMovement'] !== null) {
                $object->setDateMovement(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['DateMovement']));
            } elseif (\array_key_exists('DateMovement', $data) && $data['DateMovement'] === null) {
                $object->setDateMovement(null);
            }
            if (\array_key_exists('Notepad', $data) && $data['Notepad'] !== null) {
                $object->setNotepad($data['Notepad']);
            } elseif (\array_key_exists('Notepad', $data) && $data['Notepad'] === null) {
                $object->setNotepad(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            $data['Warehouse'] = $object->getWarehouse();
            $values = [];
            foreach ($object->getMovements() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data['Movements'] = $values;
            $data['DestinationLocation'] = $object->getDestinationLocation();
            if ($object->isInitialized('destinationAvailabilityStatus') && null !== $object->getDestinationAvailabilityStatus()) {
                $data['DestinationAvailabilityStatus'] = $object->getDestinationAvailabilityStatus();
            }
            if ($object->isInitialized('destinationFluxStatus') && null !== $object->getDestinationFluxStatus()) {
                $data['DestinationFluxStatus'] = $object->getDestinationFluxStatus();
            }
            if ($object->isInitialized('dateMovement') && null !== $object->getDateMovement()) {
                $data['DateMovement'] = $object->getDateMovement()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('notepad') && null !== $object->getNotepad()) {
                $data['Notepad'] = $object->getNotepad();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters' => false];
        }
    }
} else {
    class CegidMtsStockModelsChangeLocationParametersNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsStockModelsChangeLocationParameters();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Warehouse', $data) && $data['Warehouse'] !== null) {
                $object->setWarehouse($data['Warehouse']);
            } elseif (\array_key_exists('Warehouse', $data) && $data['Warehouse'] === null) {
                $object->setWarehouse(null);
            }
            if (\array_key_exists('Movements', $data) && $data['Movements'] !== null) {
                $values = [];
                foreach ($data['Movements'] as $value) {
                    $values[] = $this->denormalizer->denormalize($value, 'Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationRowParameters', 'json', $context);
                }
                $object->setMovements($values);
            } elseif (\array_key_exists('Movements', $data) && $data['Movements'] === null) {
                $object->setMovements(null);
            }
            if (\array_key_exists('DestinationLocation', $data) && $data['DestinationLocation'] !== null) {
                $object->setDestinationLocation($data['DestinationLocation']);
            } elseif (\array_key_exists('DestinationLocation', $data) && $data['DestinationLocation'] === null) {
                $object->setDestinationLocation(null);
            }
            if (\array_key_exists('DestinationAvailabilityStatus', $data) && $data['DestinationAvailabilityStatus'] !== null) {
                $object->setDestinationAvailabilityStatus($data['DestinationAvailabilityStatus']);
            } elseif (\array_key_exists('DestinationAvailabilityStatus', $data) && $data['DestinationAvailabilityStatus'] === null) {
                $object->setDestinationAvailabilityStatus(null);
            }
            if (\array_key_exists('DestinationFluxStatus', $data) && $data['DestinationFluxStatus'] !== null) {
                $object->setDestinationFluxStatus($data['DestinationFluxStatus']);
            } elseif (\array_key_exists('DestinationFluxStatus', $data) && $data['DestinationFluxStatus'] === null) {
                $object->setDestinationFluxStatus(null);
            }
            if (\array_key_exists('DateMovement', $data) && $data['DateMovement'] !== null) {
                $object->setDateMovement(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['DateMovement']));
            } elseif (\array_key_exists('DateMovement', $data) && $data['DateMovement'] === null) {
                $object->setDateMovement(null);
            }
            if (\array_key_exists('Notepad', $data) && $data['Notepad'] !== null) {
                $object->setNotepad($data['Notepad']);
            } elseif (\array_key_exists('Notepad', $data) && $data['Notepad'] === null) {
                $object->setNotepad(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            $data['Warehouse'] = $object->getWarehouse();
            $values = [];
            foreach ($object->getMovements() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data['Movements'] = $values;
            $data['DestinationLocation'] = $object->getDestinationLocation();
            if ($object->isInitialized('destinationAvailabilityStatus') && null !== $object->getDestinationAvailabilityStatus()) {
                $data['DestinationAvailabilityStatus'] = $object->getDestinationAvailabilityStatus();
            }
            if ($object->isInitialized('destinationFluxStatus') && null !== $object->getDestinationFluxStatus()) {
                $data['DestinationFluxStatus'] = $object->getDestinationFluxStatus();
            }
            if ($object->isInitialized('dateMovement') && null !== $object->getDateMovement()) {
                $data['DateMovement'] = $object->getDateMovement()->format('Y-m-d\\TH:i:sP');
            }
            if ($object->isInitialized('notepad') && null !== $object->getNotepad()) {
                $data['Notepad'] = $object->getNotepad();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsStockModelsChangeLocationParameters' => false];
        }
    }
}
