<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsSalesOrderAddressDtoCNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsSalesOrderAddressDtoC();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Address1', $data) && $data['Address1'] !== null) {
                $object->setAddress1($data['Address1']);
            } elseif (\array_key_exists('Address1', $data) && $data['Address1'] === null) {
                $object->setAddress1(null);
            }
            if (\array_key_exists('Address2', $data) && $data['Address2'] !== null) {
                $object->setAddress2($data['Address2']);
            } elseif (\array_key_exists('Address2', $data) && $data['Address2'] === null) {
                $object->setAddress2(null);
            }
            if (\array_key_exists('Address3', $data) && $data['Address3'] !== null) {
                $object->setAddress3($data['Address3']);
            } elseif (\array_key_exists('Address3', $data) && $data['Address3'] === null) {
                $object->setAddress3(null);
            }
            if (\array_key_exists('AdditionalCompanyName', $data) && $data['AdditionalCompanyName'] !== null) {
                $object->setAdditionalCompanyName($data['AdditionalCompanyName']);
            } elseif (\array_key_exists('AdditionalCompanyName', $data) && $data['AdditionalCompanyName'] === null) {
                $object->setAdditionalCompanyName(null);
            }
            if (\array_key_exists('CompanyName', $data) && $data['CompanyName'] !== null) {
                $object->setCompanyName($data['CompanyName']);
            } elseif (\array_key_exists('CompanyName', $data) && $data['CompanyName'] === null) {
                $object->setCompanyName(null);
            }
            if (\array_key_exists('LegalFormCode', $data) && $data['LegalFormCode'] !== null) {
                $object->setLegalFormCode($data['LegalFormCode']);
            } elseif (\array_key_exists('LegalFormCode', $data) && $data['LegalFormCode'] === null) {
                $object->setLegalFormCode(null);
            }
            if (\array_key_exists('ZipCode', $data) && $data['ZipCode'] !== null) {
                $object->setZipCode($data['ZipCode']);
            } elseif (\array_key_exists('ZipCode', $data) && $data['ZipCode'] === null) {
                $object->setZipCode(null);
            }
            if (\array_key_exists('City', $data) && $data['City'] !== null) {
                $object->setCity($data['City']);
            } elseif (\array_key_exists('City', $data) && $data['City'] === null) {
                $object->setCity(null);
            }
            if (\array_key_exists('CountryCode', $data) && $data['CountryCode'] !== null) {
                $object->setCountryCode($data['CountryCode']);
            } elseif (\array_key_exists('CountryCode', $data) && $data['CountryCode'] === null) {
                $object->setCountryCode(null);
            }
            if (\array_key_exists('Carrier', $data) && $data['Carrier'] !== null) {
                $object->setCarrier($data['Carrier']);
            } elseif (\array_key_exists('Carrier', $data) && $data['Carrier'] === null) {
                $object->setCarrier(null);
            }
            if (\array_key_exists('ShippingMethodCode', $data) && $data['ShippingMethodCode'] !== null) {
                $object->setShippingMethodCode($data['ShippingMethodCode']);
            } elseif (\array_key_exists('ShippingMethodCode', $data) && $data['ShippingMethodCode'] === null) {
                $object->setShippingMethodCode(null);
            }
            if (\array_key_exists('IncotermCode', $data) && $data['IncotermCode'] !== null) {
                $object->setIncotermCode($data['IncotermCode']);
            } elseif (\array_key_exists('IncotermCode', $data) && $data['IncotermCode'] === null) {
                $object->setIncotermCode(null);
            }
            if (\array_key_exists('AvailabilitySiteCode', $data) && $data['AvailabilitySiteCode'] !== null) {
                $object->setAvailabilitySiteCode($data['AvailabilitySiteCode']);
            } elseif (\array_key_exists('AvailabilitySiteCode', $data) && $data['AvailabilitySiteCode'] === null) {
                $object->setAvailabilitySiteCode(null);
            }
            if (\array_key_exists('TinCode', $data) && $data['TinCode'] !== null) {
                $object->setTinCode($data['TinCode']);
            } elseif (\array_key_exists('TinCode', $data) && $data['TinCode'] === null) {
                $object->setTinCode(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('address1') && null !== $object->getAddress1()) {
                $data['Address1'] = $object->getAddress1();
            }
            if ($object->isInitialized('address2') && null !== $object->getAddress2()) {
                $data['Address2'] = $object->getAddress2();
            }
            if ($object->isInitialized('address3') && null !== $object->getAddress3()) {
                $data['Address3'] = $object->getAddress3();
            }
            if ($object->isInitialized('additionalCompanyName') && null !== $object->getAdditionalCompanyName()) {
                $data['AdditionalCompanyName'] = $object->getAdditionalCompanyName();
            }
            if ($object->isInitialized('companyName') && null !== $object->getCompanyName()) {
                $data['CompanyName'] = $object->getCompanyName();
            }
            if ($object->isInitialized('legalFormCode') && null !== $object->getLegalFormCode()) {
                $data['LegalFormCode'] = $object->getLegalFormCode();
            }
            if ($object->isInitialized('zipCode') && null !== $object->getZipCode()) {
                $data['ZipCode'] = $object->getZipCode();
            }
            if ($object->isInitialized('city') && null !== $object->getCity()) {
                $data['City'] = $object->getCity();
            }
            if ($object->isInitialized('countryCode') && null !== $object->getCountryCode()) {
                $data['CountryCode'] = $object->getCountryCode();
            }
            if ($object->isInitialized('carrier') && null !== $object->getCarrier()) {
                $data['Carrier'] = $object->getCarrier();
            }
            if ($object->isInitialized('shippingMethodCode') && null !== $object->getShippingMethodCode()) {
                $data['ShippingMethodCode'] = $object->getShippingMethodCode();
            }
            if ($object->isInitialized('incotermCode') && null !== $object->getIncotermCode()) {
                $data['IncotermCode'] = $object->getIncotermCode();
            }
            if ($object->isInitialized('availabilitySiteCode') && null !== $object->getAvailabilitySiteCode()) {
                $data['AvailabilitySiteCode'] = $object->getAvailabilitySiteCode();
            }
            if ($object->isInitialized('tinCode') && null !== $object->getTinCode()) {
                $data['TinCode'] = $object->getTinCode();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC' => false];
        }
    }
} else {
    class CegidMtsSalesOrderAddressDtoCNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsSalesOrderAddressDtoC();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('Address1', $data) && $data['Address1'] !== null) {
                $object->setAddress1($data['Address1']);
            } elseif (\array_key_exists('Address1', $data) && $data['Address1'] === null) {
                $object->setAddress1(null);
            }
            if (\array_key_exists('Address2', $data) && $data['Address2'] !== null) {
                $object->setAddress2($data['Address2']);
            } elseif (\array_key_exists('Address2', $data) && $data['Address2'] === null) {
                $object->setAddress2(null);
            }
            if (\array_key_exists('Address3', $data) && $data['Address3'] !== null) {
                $object->setAddress3($data['Address3']);
            } elseif (\array_key_exists('Address3', $data) && $data['Address3'] === null) {
                $object->setAddress3(null);
            }
            if (\array_key_exists('AdditionalCompanyName', $data) && $data['AdditionalCompanyName'] !== null) {
                $object->setAdditionalCompanyName($data['AdditionalCompanyName']);
            } elseif (\array_key_exists('AdditionalCompanyName', $data) && $data['AdditionalCompanyName'] === null) {
                $object->setAdditionalCompanyName(null);
            }
            if (\array_key_exists('CompanyName', $data) && $data['CompanyName'] !== null) {
                $object->setCompanyName($data['CompanyName']);
            } elseif (\array_key_exists('CompanyName', $data) && $data['CompanyName'] === null) {
                $object->setCompanyName(null);
            }
            if (\array_key_exists('LegalFormCode', $data) && $data['LegalFormCode'] !== null) {
                $object->setLegalFormCode($data['LegalFormCode']);
            } elseif (\array_key_exists('LegalFormCode', $data) && $data['LegalFormCode'] === null) {
                $object->setLegalFormCode(null);
            }
            if (\array_key_exists('ZipCode', $data) && $data['ZipCode'] !== null) {
                $object->setZipCode($data['ZipCode']);
            } elseif (\array_key_exists('ZipCode', $data) && $data['ZipCode'] === null) {
                $object->setZipCode(null);
            }
            if (\array_key_exists('City', $data) && $data['City'] !== null) {
                $object->setCity($data['City']);
            } elseif (\array_key_exists('City', $data) && $data['City'] === null) {
                $object->setCity(null);
            }
            if (\array_key_exists('CountryCode', $data) && $data['CountryCode'] !== null) {
                $object->setCountryCode($data['CountryCode']);
            } elseif (\array_key_exists('CountryCode', $data) && $data['CountryCode'] === null) {
                $object->setCountryCode(null);
            }
            if (\array_key_exists('Carrier', $data) && $data['Carrier'] !== null) {
                $object->setCarrier($data['Carrier']);
            } elseif (\array_key_exists('Carrier', $data) && $data['Carrier'] === null) {
                $object->setCarrier(null);
            }
            if (\array_key_exists('ShippingMethodCode', $data) && $data['ShippingMethodCode'] !== null) {
                $object->setShippingMethodCode($data['ShippingMethodCode']);
            } elseif (\array_key_exists('ShippingMethodCode', $data) && $data['ShippingMethodCode'] === null) {
                $object->setShippingMethodCode(null);
            }
            if (\array_key_exists('IncotermCode', $data) && $data['IncotermCode'] !== null) {
                $object->setIncotermCode($data['IncotermCode']);
            } elseif (\array_key_exists('IncotermCode', $data) && $data['IncotermCode'] === null) {
                $object->setIncotermCode(null);
            }
            if (\array_key_exists('AvailabilitySiteCode', $data) && $data['AvailabilitySiteCode'] !== null) {
                $object->setAvailabilitySiteCode($data['AvailabilitySiteCode']);
            } elseif (\array_key_exists('AvailabilitySiteCode', $data) && $data['AvailabilitySiteCode'] === null) {
                $object->setAvailabilitySiteCode(null);
            }
            if (\array_key_exists('TinCode', $data) && $data['TinCode'] !== null) {
                $object->setTinCode($data['TinCode']);
            } elseif (\array_key_exists('TinCode', $data) && $data['TinCode'] === null) {
                $object->setTinCode(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('address1') && null !== $object->getAddress1()) {
                $data['Address1'] = $object->getAddress1();
            }
            if ($object->isInitialized('address2') && null !== $object->getAddress2()) {
                $data['Address2'] = $object->getAddress2();
            }
            if ($object->isInitialized('address3') && null !== $object->getAddress3()) {
                $data['Address3'] = $object->getAddress3();
            }
            if ($object->isInitialized('additionalCompanyName') && null !== $object->getAdditionalCompanyName()) {
                $data['AdditionalCompanyName'] = $object->getAdditionalCompanyName();
            }
            if ($object->isInitialized('companyName') && null !== $object->getCompanyName()) {
                $data['CompanyName'] = $object->getCompanyName();
            }
            if ($object->isInitialized('legalFormCode') && null !== $object->getLegalFormCode()) {
                $data['LegalFormCode'] = $object->getLegalFormCode();
            }
            if ($object->isInitialized('zipCode') && null !== $object->getZipCode()) {
                $data['ZipCode'] = $object->getZipCode();
            }
            if ($object->isInitialized('city') && null !== $object->getCity()) {
                $data['City'] = $object->getCity();
            }
            if ($object->isInitialized('countryCode') && null !== $object->getCountryCode()) {
                $data['CountryCode'] = $object->getCountryCode();
            }
            if ($object->isInitialized('carrier') && null !== $object->getCarrier()) {
                $data['Carrier'] = $object->getCarrier();
            }
            if ($object->isInitialized('shippingMethodCode') && null !== $object->getShippingMethodCode()) {
                $data['ShippingMethodCode'] = $object->getShippingMethodCode();
            }
            if ($object->isInitialized('incotermCode') && null !== $object->getIncotermCode()) {
                $data['IncotermCode'] = $object->getIncotermCode();
            }
            if ($object->isInitialized('availabilitySiteCode') && null !== $object->getAvailabilitySiteCode()) {
                $data['AvailabilitySiteCode'] = $object->getAvailabilitySiteCode();
            }
            if ($object->isInitialized('tinCode') && null !== $object->getTinCode()) {
                $data['TinCode'] = $object->getTinCode();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsSalesOrderAddressDtoC' => false];
        }
    }
}
