<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Normalizer;

use Cegid\Api\Runtime\Normalizer\CheckArray;
use Cegid\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class CegidMtsSalesOrderContractUserDefinedDataDtoNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto';
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsSalesOrderContractUserDefinedDataDto();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('UserDefinedTable1Code', $data) && $data['UserDefinedTable1Code'] !== null) {
                $object->setUserDefinedTable1Code($data['UserDefinedTable1Code']);
            } elseif (\array_key_exists('UserDefinedTable1Code', $data) && $data['UserDefinedTable1Code'] === null) {
                $object->setUserDefinedTable1Code(null);
            }
            if (\array_key_exists('UserDefinedTable2Code', $data) && $data['UserDefinedTable2Code'] !== null) {
                $object->setUserDefinedTable2Code($data['UserDefinedTable2Code']);
            } elseif (\array_key_exists('UserDefinedTable2Code', $data) && $data['UserDefinedTable2Code'] === null) {
                $object->setUserDefinedTable2Code(null);
            }
            if (\array_key_exists('UserDefinedTable3Code', $data) && $data['UserDefinedTable3Code'] !== null) {
                $object->setUserDefinedTable3Code($data['UserDefinedTable3Code']);
            } elseif (\array_key_exists('UserDefinedTable3Code', $data) && $data['UserDefinedTable3Code'] === null) {
                $object->setUserDefinedTable3Code(null);
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('userDefinedTable1Code') && null !== $object->getUserDefinedTable1Code()) {
                $data['UserDefinedTable1Code'] = $object->getUserDefinedTable1Code();
            }
            if ($object->isInitialized('userDefinedTable2Code') && null !== $object->getUserDefinedTable2Code()) {
                $data['UserDefinedTable2Code'] = $object->getUserDefinedTable2Code();
            }
            if ($object->isInitialized('userDefinedTable3Code') && null !== $object->getUserDefinedTable3Code()) {
                $data['UserDefinedTable3Code'] = $object->getUserDefinedTable3Code();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto' => false];
        }
    }
} else {
    class CegidMtsSalesOrderContractUserDefinedDataDtoNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === 'Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto';
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Cegid\Api\Model\CegidMtsSalesOrderContractUserDefinedDataDto();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('UserDefinedTable1Code', $data) && $data['UserDefinedTable1Code'] !== null) {
                $object->setUserDefinedTable1Code($data['UserDefinedTable1Code']);
            } elseif (\array_key_exists('UserDefinedTable1Code', $data) && $data['UserDefinedTable1Code'] === null) {
                $object->setUserDefinedTable1Code(null);
            }
            if (\array_key_exists('UserDefinedTable2Code', $data) && $data['UserDefinedTable2Code'] !== null) {
                $object->setUserDefinedTable2Code($data['UserDefinedTable2Code']);
            } elseif (\array_key_exists('UserDefinedTable2Code', $data) && $data['UserDefinedTable2Code'] === null) {
                $object->setUserDefinedTable2Code(null);
            }
            if (\array_key_exists('UserDefinedTable3Code', $data) && $data['UserDefinedTable3Code'] !== null) {
                $object->setUserDefinedTable3Code($data['UserDefinedTable3Code']);
            } elseif (\array_key_exists('UserDefinedTable3Code', $data) && $data['UserDefinedTable3Code'] === null) {
                $object->setUserDefinedTable3Code(null);
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('userDefinedTable1Code') && null !== $object->getUserDefinedTable1Code()) {
                $data['UserDefinedTable1Code'] = $object->getUserDefinedTable1Code();
            }
            if ($object->isInitialized('userDefinedTable2Code') && null !== $object->getUserDefinedTable2Code()) {
                $data['UserDefinedTable2Code'] = $object->getUserDefinedTable2Code();
            }
            if ($object->isInitialized('userDefinedTable3Code') && null !== $object->getUserDefinedTable3Code()) {
                $data['UserDefinedTable3Code'] = $object->getUserDefinedTable3Code();
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return ['Cegid\\Api\\Model\\CegidMtsSalesOrderContractUserDefinedDataDto' => false];
        }
    }
}
