<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsAddressesEntityCustomerAddressKey
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int|null
     */
    protected $internalAddressNumber;
    /**
     * @var mixed|null
     */
    protected $addressType;

    public function getInternalAddressNumber(): ?int
    {
        return $this->internalAddressNumber;
    }

    public function setInternalAddressNumber(?int $internalAddressNumber): self
    {
        $this->initialized['internalAddressNumber'] = true;
        $this->internalAddressNumber = $internalAddressNumber;

        return $this;
    }

    public function getAddressType()
    {
        return $this->addressType;
    }

    public function setAddressType($addressType): self
    {
        $this->initialized['addressType'] = true;
        $this->addressType = $addressType;

        return $this;
    }
}
