<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsBusinessSideCbsImportFileDto
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Nom du fichier à importer.
     *
     * @var string|null
     */
    protected $fileName;
    /**
     * Format des dates dans le fichier d'import.
     *
     * @var string|null
     */
    protected $dateFormat;
    /**
     * Format des heures dans le fichier d'import.
     *
     * @var string|null
     */
    protected $timeFormat;
    /**
     * Séparateur décimal des valeurs numériques.
     *
     * @var string|null
     */
    protected $decimalSeparator;
    /**
     * Caractère séparateur des noms de champs sur la première ligne des fichiers csv.
     *
     * @var string|null
     */
    protected $csvDelimiterChar;
    /**
     * Contenu zippé du fichier à importer.
     *
     * @var string|null
     */
    protected $content;

    /**
     * Nom du fichier à importer.
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * Nom du fichier à importer.
     */
    public function setFileName(?string $fileName): self
    {
        $this->initialized['fileName'] = true;
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * Format des dates dans le fichier d'import.
     */
    public function getDateFormat(): ?string
    {
        return $this->dateFormat;
    }

    /**
     * Format des dates dans le fichier d'import.
     */
    public function setDateFormat(?string $dateFormat): self
    {
        $this->initialized['dateFormat'] = true;
        $this->dateFormat = $dateFormat;

        return $this;
    }

    /**
     * Format des heures dans le fichier d'import.
     */
    public function getTimeFormat(): ?string
    {
        return $this->timeFormat;
    }

    /**
     * Format des heures dans le fichier d'import.
     */
    public function setTimeFormat(?string $timeFormat): self
    {
        $this->initialized['timeFormat'] = true;
        $this->timeFormat = $timeFormat;

        return $this;
    }

    /**
     * Séparateur décimal des valeurs numériques.
     */
    public function getDecimalSeparator(): ?string
    {
        return $this->decimalSeparator;
    }

    /**
     * Séparateur décimal des valeurs numériques.
     */
    public function setDecimalSeparator(?string $decimalSeparator): self
    {
        $this->initialized['decimalSeparator'] = true;
        $this->decimalSeparator = $decimalSeparator;

        return $this;
    }

    /**
     * Caractère séparateur des noms de champs sur la première ligne des fichiers csv.
     */
    public function getCsvDelimiterChar(): ?string
    {
        return $this->csvDelimiterChar;
    }

    /**
     * Caractère séparateur des noms de champs sur la première ligne des fichiers csv.
     */
    public function setCsvDelimiterChar(?string $csvDelimiterChar): self
    {
        $this->initialized['csvDelimiterChar'] = true;
        $this->csvDelimiterChar = $csvDelimiterChar;

        return $this;
    }

    /**
     * Contenu zippé du fichier à importer.
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Contenu zippé du fichier à importer.
     */
    public function setContent(?string $content): self
    {
        $this->initialized['content'] = true;
        $this->content = $content;

        return $this;
    }
}
