<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsStockModelsManualOutputParameters
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Motif du mouvement.
     *
     * @var string|null
     */
    protected $motive;
    /**
     * Date du mouvement.
     *
     * @var \DateTime|null
     */
    protected $dateMovement;
    /**
     * Quantité (Unité de stock).
     *
     * @var float|null
     */
    protected $quantity;
    /**
     * @var CegidMtsStockModelsManualMovementStockDetailKey|null
     */
    protected $stockDetailKey;
    /**
     * Code affaire.
     *
     * @var string|null
     */
    protected $contract;
    /**
     * Bloc-note.
     *
     * @var string|null
     */
    protected $notepad;

    /**
     * Motif du mouvement.
     */
    public function getMotive(): ?string
    {
        return $this->motive;
    }

    /**
     * Motif du mouvement.
     */
    public function setMotive(?string $motive): self
    {
        $this->initialized['motive'] = true;
        $this->motive = $motive;

        return $this;
    }

    /**
     * Date du mouvement.
     */
    public function getDateMovement(): ?\DateTime
    {
        return $this->dateMovement;
    }

    /**
     * Date du mouvement.
     */
    public function setDateMovement(?\DateTime $dateMovement): self
    {
        $this->initialized['dateMovement'] = true;
        $this->dateMovement = $dateMovement;

        return $this;
    }

    /**
     * Quantité (Unité de stock).
     */
    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    /**
     * Quantité (Unité de stock).
     */
    public function setQuantity(?float $quantity): self
    {
        $this->initialized['quantity'] = true;
        $this->quantity = $quantity;

        return $this;
    }

    public function getStockDetailKey(): ?CegidMtsStockModelsManualMovementStockDetailKey
    {
        return $this->stockDetailKey;
    }

    public function setStockDetailKey(?CegidMtsStockModelsManualMovementStockDetailKey $stockDetailKey): self
    {
        $this->initialized['stockDetailKey'] = true;
        $this->stockDetailKey = $stockDetailKey;

        return $this;
    }

    /**
     * Code affaire.
     */
    public function getContract(): ?string
    {
        return $this->contract;
    }

    /**
     * Code affaire.
     */
    public function setContract(?string $contract): self
    {
        $this->initialized['contract'] = true;
        $this->contract = $contract;

        return $this;
    }

    /**
     * Bloc-note.
     */
    public function getNotepad(): ?string
    {
        return $this->notepad;
    }

    /**
     * Bloc-note.
     */
    public function setNotepad(?string $notepad): self
    {
        $this->initialized['notepad'] = true;
        $this->notepad = $notepad;

        return $this;
    }
}
