<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsProductEntityUserDefinedData
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var CegidMtsProductEntityUserDefinedDecisions|null
     */
    protected $decisions;
    /**
     * @var CegidMtsProductEntityUserDefinedTables|null
     */
    protected $tables;
    /**
     * @var CegidMtsProductEntityUserDefinedTexts|null
     */
    protected $texts;
    /**
     * @var CegidMtsProductEntityUserDefinedValues|null
     */
    protected $values;
    /**
     * @var CegidMtsProductEntityUserDefinedDates|null
     */
    protected $dates;

    public function getDecisions(): ?CegidMtsProductEntityUserDefinedDecisions
    {
        return $this->decisions;
    }

    public function setDecisions(?CegidMtsProductEntityUserDefinedDecisions $decisions): self
    {
        $this->initialized['decisions'] = true;
        $this->decisions = $decisions;

        return $this;
    }

    public function getTables(): ?CegidMtsProductEntityUserDefinedTables
    {
        return $this->tables;
    }

    public function setTables(?CegidMtsProductEntityUserDefinedTables $tables): self
    {
        $this->initialized['tables'] = true;
        $this->tables = $tables;

        return $this;
    }

    public function getTexts(): ?CegidMtsProductEntityUserDefinedTexts
    {
        return $this->texts;
    }

    public function setTexts(?CegidMtsProductEntityUserDefinedTexts $texts): self
    {
        $this->initialized['texts'] = true;
        $this->texts = $texts;

        return $this;
    }

    public function getValues(): ?CegidMtsProductEntityUserDefinedValues
    {
        return $this->values;
    }

    public function setValues(?CegidMtsProductEntityUserDefinedValues $values): self
    {
        $this->initialized['values'] = true;
        $this->values = $values;

        return $this;
    }

    public function getDates(): ?CegidMtsProductEntityUserDefinedDates
    {
        return $this->dates;
    }

    public function setDates(?CegidMtsProductEntityUserDefinedDates $dates): self
    {
        $this->initialized['dates'] = true;
        $this->dates = $dates;

        return $this;
    }
}
