<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsActivityExpensesSheetExpensesSheetBaseDto
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * N° de la note de frais.
     *
     * @var int|null
     */
    protected $id;
    /**
     * Code de la ressource.
     *
     * @var string|null
     */
    protected $resource;
    /**
     * Date de début de la période.
     *
     * @var \DateTime|null
     */
    protected $periodStartDate;
    /**
     * Date de fin de la période.
     *
     * @var \DateTime|null
     */
    protected $periodEndDate;
    /**
     * Date de soumission.
     *
     * @var \DateTime|null
     */
    protected $submittedDate;
    /**
     * Statut.
     *
     * @var string|null
     */
    protected $state;
    /**
     * Montant TTC soumis.
     *
     * @var float|null
     */
    protected $submittedAmountTaxIncluding;
    /**
     * Montant TTC visé.
     *
     * @var float|null
     */
    protected $approvalAmountTaxIncluding;
    /**
     * Référence comptable.
     *
     * @var string|null
     */
    protected $accountingReference;
    /**
     * Commentaires.
     *
     * @var string|null
     */
    protected $comments;
    /**
     * Date de la dernière action.
     *
     * @var \DateTime|null
     */
    protected $lastActionDate;
    /**
     * Code ressource de la dernière action.
     *
     * @var string|null
     */
    protected $lastActionResource;
    /**
     * Date de création.
     *
     * @var \DateTime|null
     */
    protected $creationDate;
    /**
     * Date de modification.
     *
     * @var \DateTime|null
     */
    protected $modificationDate;
    /**
     * Créé par.
     *
     * @var string|null
     */
    protected $createdBy;
    /**
     * Modifié par.
     *
     * @var string|null
     */
    protected $modifiedBy;

    /**
     * N° de la note de frais.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * N° de la note de frais.
     */
    public function setId(?int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * Code de la ressource.
     */
    public function getResource(): ?string
    {
        return $this->resource;
    }

    /**
     * Code de la ressource.
     */
    public function setResource(?string $resource): self
    {
        $this->initialized['resource'] = true;
        $this->resource = $resource;

        return $this;
    }

    /**
     * Date de début de la période.
     */
    public function getPeriodStartDate(): ?\DateTime
    {
        return $this->periodStartDate;
    }

    /**
     * Date de début de la période.
     */
    public function setPeriodStartDate(?\DateTime $periodStartDate): self
    {
        $this->initialized['periodStartDate'] = true;
        $this->periodStartDate = $periodStartDate;

        return $this;
    }

    /**
     * Date de fin de la période.
     */
    public function getPeriodEndDate(): ?\DateTime
    {
        return $this->periodEndDate;
    }

    /**
     * Date de fin de la période.
     */
    public function setPeriodEndDate(?\DateTime $periodEndDate): self
    {
        $this->initialized['periodEndDate'] = true;
        $this->periodEndDate = $periodEndDate;

        return $this;
    }

    /**
     * Date de soumission.
     */
    public function getSubmittedDate(): ?\DateTime
    {
        return $this->submittedDate;
    }

    /**
     * Date de soumission.
     */
    public function setSubmittedDate(?\DateTime $submittedDate): self
    {
        $this->initialized['submittedDate'] = true;
        $this->submittedDate = $submittedDate;

        return $this;
    }

    /**
     * Statut.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Statut.
     */
    public function setState(?string $state): self
    {
        $this->initialized['state'] = true;
        $this->state = $state;

        return $this;
    }

    /**
     * Montant TTC soumis.
     */
    public function getSubmittedAmountTaxIncluding(): ?float
    {
        return $this->submittedAmountTaxIncluding;
    }

    /**
     * Montant TTC soumis.
     */
    public function setSubmittedAmountTaxIncluding(?float $submittedAmountTaxIncluding): self
    {
        $this->initialized['submittedAmountTaxIncluding'] = true;
        $this->submittedAmountTaxIncluding = $submittedAmountTaxIncluding;

        return $this;
    }

    /**
     * Montant TTC visé.
     */
    public function getApprovalAmountTaxIncluding(): ?float
    {
        return $this->approvalAmountTaxIncluding;
    }

    /**
     * Montant TTC visé.
     */
    public function setApprovalAmountTaxIncluding(?float $approvalAmountTaxIncluding): self
    {
        $this->initialized['approvalAmountTaxIncluding'] = true;
        $this->approvalAmountTaxIncluding = $approvalAmountTaxIncluding;

        return $this;
    }

    /**
     * Référence comptable.
     */
    public function getAccountingReference(): ?string
    {
        return $this->accountingReference;
    }

    /**
     * Référence comptable.
     */
    public function setAccountingReference(?string $accountingReference): self
    {
        $this->initialized['accountingReference'] = true;
        $this->accountingReference = $accountingReference;

        return $this;
    }

    /**
     * Commentaires.
     */
    public function getComments(): ?string
    {
        return $this->comments;
    }

    /**
     * Commentaires.
     */
    public function setComments(?string $comments): self
    {
        $this->initialized['comments'] = true;
        $this->comments = $comments;

        return $this;
    }

    /**
     * Date de la dernière action.
     */
    public function getLastActionDate(): ?\DateTime
    {
        return $this->lastActionDate;
    }

    /**
     * Date de la dernière action.
     */
    public function setLastActionDate(?\DateTime $lastActionDate): self
    {
        $this->initialized['lastActionDate'] = true;
        $this->lastActionDate = $lastActionDate;

        return $this;
    }

    /**
     * Code ressource de la dernière action.
     */
    public function getLastActionResource(): ?string
    {
        return $this->lastActionResource;
    }

    /**
     * Code ressource de la dernière action.
     */
    public function setLastActionResource(?string $lastActionResource): self
    {
        $this->initialized['lastActionResource'] = true;
        $this->lastActionResource = $lastActionResource;

        return $this;
    }

    /**
     * Date de création.
     */
    public function getCreationDate(): ?\DateTime
    {
        return $this->creationDate;
    }

    /**
     * Date de création.
     */
    public function setCreationDate(?\DateTime $creationDate): self
    {
        $this->initialized['creationDate'] = true;
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Date de modification.
     */
    public function getModificationDate(): ?\DateTime
    {
        return $this->modificationDate;
    }

    /**
     * Date de modification.
     */
    public function setModificationDate(?\DateTime $modificationDate): self
    {
        $this->initialized['modificationDate'] = true;
        $this->modificationDate = $modificationDate;

        return $this;
    }

    /**
     * Créé par.
     */
    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    /**
     * Créé par.
     */
    public function setCreatedBy(?string $createdBy): self
    {
        $this->initialized['createdBy'] = true;
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Modifié par.
     */
    public function getModifiedBy(): ?string
    {
        return $this->modifiedBy;
    }

    /**
     * Modifié par.
     */
    public function setModifiedBy(?string $modifiedBy): self
    {
        $this->initialized['modifiedBy'] = true;
        $this->modifiedBy = $modifiedBy;

        return $this;
    }
}
