<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsThirdPartyEntitiesV1SalesRepresentativeDtoReader
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Type.
     *
     * @var string|null
     */
    protected $type;
    /**
     * Libellé du type.
     *
     * @var string|null
     */
    protected $typeLabel;
    /**
     * Code.
     *
     * @var string|null
     */
    protected $code;
    /**
     * Nom.
     *
     * @var string|null
     */
    protected $label;
    /**
     * Prénom.
     *
     * @var string|null
     */
    protected $firstName;
    /**
     * Code établissement.
     *
     * @var string|null
     */
    protected $businessCenter;
    /**
     * Libellé établissement.
     *
     * @var string|null
     */
    protected $businessCenterLabel;
    /**
     * Code du salarié associé.
     *
     * @var string|null
     */
    protected $employee;
    /**
     * Libellé du salarié associé.
     *
     * @var string|null
     */
    protected $employeeLabel;
    /**
     * Pourcentage de commission.
     *
     * @var float|null
     */
    protected $commissionPercentage;
    /**
     * Code de l'utilisateur associé.
     *
     * @var string|null
     */
    protected $associatedUser;
    /**
     * Libellé de l'utilisateur associé.
     *
     * @var string|null
     */
    protected $associatedUserLabel;
    /**
     * Valeur libre 1.
     *
     * @var float|null
     */
    protected $userDefinedValue1;
    /**
     * Valeur libre 2.
     *
     * @var float|null
     */
    protected $userDefinedValue2;
    /**
     * Valeur libre 3.
     *
     * @var float|null
     */
    protected $userDefinedValue3;
    /**
     * Date libre 1.
     *
     * @var \DateTime|null
     */
    protected $userDefinedDate1;
    /**
     * Date libre 2.
     *
     * @var \DateTime|null
     */
    protected $userDefinedDate2;
    /**
     * Date libre 3.
     *
     * @var \DateTime|null
     */
    protected $userDefinedDate3;
    /**
     * Code de la zone commerciale.
     *
     * @var string|null
     */
    protected $commercialArea;
    /**
     * Libellé de la zone commerciale.
     *
     * @var string|null
     */
    protected $commercialAreaLabel;
    /**
     * Code de la base de calcul de la commission.
     *
     * @var string|null
     */
    protected $calculationBasis;
    /**
     * Libellé de la base de calcul de la commission.
     *
     * @var string|null
     */
    protected $calculationBasisLabel;
    /**
     * Code de la nature de pièce commissionée.
     *
     * @var string|null
     */
    protected $docType;
    /**
     * Date de fermeture.
     *
     * @var \DateTime|null
     */
    protected $closedDate;
    /**
     * Email.
     *
     * @var string|null
     */
    protected $email;
    /**
     * Préfixe du code tiers.
     *
     * @var string|null
     */
    protected $thirdPartyCodePrefix;
    /**
     * Rang du serveur.
     *
     * @var string|null
     */
    protected $serverRank;
    /**
     * Commission sur encaissement.
     *
     * @var bool|null
     */
    protected $isCommissionPayment;
    /**
     * Bloc-notes.
     *
     * @var string|null
     */
    protected $notepad;

    /**
     * Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Type.
     */
    public function setType(?string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }

    /**
     * Libellé du type.
     */
    public function getTypeLabel(): ?string
    {
        return $this->typeLabel;
    }

    /**
     * Libellé du type.
     */
    public function setTypeLabel(?string $typeLabel): self
    {
        $this->initialized['typeLabel'] = true;
        $this->typeLabel = $typeLabel;

        return $this;
    }

    /**
     * Code.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Code.
     */
    public function setCode(?string $code): self
    {
        $this->initialized['code'] = true;
        $this->code = $code;

        return $this;
    }

    /**
     * Nom.
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Nom.
     */
    public function setLabel(?string $label): self
    {
        $this->initialized['label'] = true;
        $this->label = $label;

        return $this;
    }

    /**
     * Prénom.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Prénom.
     */
    public function setFirstName(?string $firstName): self
    {
        $this->initialized['firstName'] = true;
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Code établissement.
     */
    public function getBusinessCenter(): ?string
    {
        return $this->businessCenter;
    }

    /**
     * Code établissement.
     */
    public function setBusinessCenter(?string $businessCenter): self
    {
        $this->initialized['businessCenter'] = true;
        $this->businessCenter = $businessCenter;

        return $this;
    }

    /**
     * Libellé établissement.
     */
    public function getBusinessCenterLabel(): ?string
    {
        return $this->businessCenterLabel;
    }

    /**
     * Libellé établissement.
     */
    public function setBusinessCenterLabel(?string $businessCenterLabel): self
    {
        $this->initialized['businessCenterLabel'] = true;
        $this->businessCenterLabel = $businessCenterLabel;

        return $this;
    }

    /**
     * Code du salarié associé.
     */
    public function getEmployee(): ?string
    {
        return $this->employee;
    }

    /**
     * Code du salarié associé.
     */
    public function setEmployee(?string $employee): self
    {
        $this->initialized['employee'] = true;
        $this->employee = $employee;

        return $this;
    }

    /**
     * Libellé du salarié associé.
     */
    public function getEmployeeLabel(): ?string
    {
        return $this->employeeLabel;
    }

    /**
     * Libellé du salarié associé.
     */
    public function setEmployeeLabel(?string $employeeLabel): self
    {
        $this->initialized['employeeLabel'] = true;
        $this->employeeLabel = $employeeLabel;

        return $this;
    }

    /**
     * Pourcentage de commission.
     */
    public function getCommissionPercentage(): ?float
    {
        return $this->commissionPercentage;
    }

    /**
     * Pourcentage de commission.
     */
    public function setCommissionPercentage(?float $commissionPercentage): self
    {
        $this->initialized['commissionPercentage'] = true;
        $this->commissionPercentage = $commissionPercentage;

        return $this;
    }

    /**
     * Code de l'utilisateur associé.
     */
    public function getAssociatedUser(): ?string
    {
        return $this->associatedUser;
    }

    /**
     * Code de l'utilisateur associé.
     */
    public function setAssociatedUser(?string $associatedUser): self
    {
        $this->initialized['associatedUser'] = true;
        $this->associatedUser = $associatedUser;

        return $this;
    }

    /**
     * Libellé de l'utilisateur associé.
     */
    public function getAssociatedUserLabel(): ?string
    {
        return $this->associatedUserLabel;
    }

    /**
     * Libellé de l'utilisateur associé.
     */
    public function setAssociatedUserLabel(?string $associatedUserLabel): self
    {
        $this->initialized['associatedUserLabel'] = true;
        $this->associatedUserLabel = $associatedUserLabel;

        return $this;
    }

    /**
     * Valeur libre 1.
     */
    public function getUserDefinedValue1(): ?float
    {
        return $this->userDefinedValue1;
    }

    /**
     * Valeur libre 1.
     */
    public function setUserDefinedValue1(?float $userDefinedValue1): self
    {
        $this->initialized['userDefinedValue1'] = true;
        $this->userDefinedValue1 = $userDefinedValue1;

        return $this;
    }

    /**
     * Valeur libre 2.
     */
    public function getUserDefinedValue2(): ?float
    {
        return $this->userDefinedValue2;
    }

    /**
     * Valeur libre 2.
     */
    public function setUserDefinedValue2(?float $userDefinedValue2): self
    {
        $this->initialized['userDefinedValue2'] = true;
        $this->userDefinedValue2 = $userDefinedValue2;

        return $this;
    }

    /**
     * Valeur libre 3.
     */
    public function getUserDefinedValue3(): ?float
    {
        return $this->userDefinedValue3;
    }

    /**
     * Valeur libre 3.
     */
    public function setUserDefinedValue3(?float $userDefinedValue3): self
    {
        $this->initialized['userDefinedValue3'] = true;
        $this->userDefinedValue3 = $userDefinedValue3;

        return $this;
    }

    /**
     * Date libre 1.
     */
    public function getUserDefinedDate1(): ?\DateTime
    {
        return $this->userDefinedDate1;
    }

    /**
     * Date libre 1.
     */
    public function setUserDefinedDate1(?\DateTime $userDefinedDate1): self
    {
        $this->initialized['userDefinedDate1'] = true;
        $this->userDefinedDate1 = $userDefinedDate1;

        return $this;
    }

    /**
     * Date libre 2.
     */
    public function getUserDefinedDate2(): ?\DateTime
    {
        return $this->userDefinedDate2;
    }

    /**
     * Date libre 2.
     */
    public function setUserDefinedDate2(?\DateTime $userDefinedDate2): self
    {
        $this->initialized['userDefinedDate2'] = true;
        $this->userDefinedDate2 = $userDefinedDate2;

        return $this;
    }

    /**
     * Date libre 3.
     */
    public function getUserDefinedDate3(): ?\DateTime
    {
        return $this->userDefinedDate3;
    }

    /**
     * Date libre 3.
     */
    public function setUserDefinedDate3(?\DateTime $userDefinedDate3): self
    {
        $this->initialized['userDefinedDate3'] = true;
        $this->userDefinedDate3 = $userDefinedDate3;

        return $this;
    }

    /**
     * Code de la zone commerciale.
     */
    public function getCommercialArea(): ?string
    {
        return $this->commercialArea;
    }

    /**
     * Code de la zone commerciale.
     */
    public function setCommercialArea(?string $commercialArea): self
    {
        $this->initialized['commercialArea'] = true;
        $this->commercialArea = $commercialArea;

        return $this;
    }

    /**
     * Libellé de la zone commerciale.
     */
    public function getCommercialAreaLabel(): ?string
    {
        return $this->commercialAreaLabel;
    }

    /**
     * Libellé de la zone commerciale.
     */
    public function setCommercialAreaLabel(?string $commercialAreaLabel): self
    {
        $this->initialized['commercialAreaLabel'] = true;
        $this->commercialAreaLabel = $commercialAreaLabel;

        return $this;
    }

    /**
     * Code de la base de calcul de la commission.
     */
    public function getCalculationBasis(): ?string
    {
        return $this->calculationBasis;
    }

    /**
     * Code de la base de calcul de la commission.
     */
    public function setCalculationBasis(?string $calculationBasis): self
    {
        $this->initialized['calculationBasis'] = true;
        $this->calculationBasis = $calculationBasis;

        return $this;
    }

    /**
     * Libellé de la base de calcul de la commission.
     */
    public function getCalculationBasisLabel(): ?string
    {
        return $this->calculationBasisLabel;
    }

    /**
     * Libellé de la base de calcul de la commission.
     */
    public function setCalculationBasisLabel(?string $calculationBasisLabel): self
    {
        $this->initialized['calculationBasisLabel'] = true;
        $this->calculationBasisLabel = $calculationBasisLabel;

        return $this;
    }

    /**
     * Code de la nature de pièce commissionée.
     */
    public function getDocType(): ?string
    {
        return $this->docType;
    }

    /**
     * Code de la nature de pièce commissionée.
     */
    public function setDocType(?string $docType): self
    {
        $this->initialized['docType'] = true;
        $this->docType = $docType;

        return $this;
    }

    /**
     * Date de fermeture.
     */
    public function getClosedDate(): ?\DateTime
    {
        return $this->closedDate;
    }

    /**
     * Date de fermeture.
     */
    public function setClosedDate(?\DateTime $closedDate): self
    {
        $this->initialized['closedDate'] = true;
        $this->closedDate = $closedDate;

        return $this;
    }

    /**
     * Email.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Email.
     */
    public function setEmail(?string $email): self
    {
        $this->initialized['email'] = true;
        $this->email = $email;

        return $this;
    }

    /**
     * Préfixe du code tiers.
     */
    public function getThirdPartyCodePrefix(): ?string
    {
        return $this->thirdPartyCodePrefix;
    }

    /**
     * Préfixe du code tiers.
     */
    public function setThirdPartyCodePrefix(?string $thirdPartyCodePrefix): self
    {
        $this->initialized['thirdPartyCodePrefix'] = true;
        $this->thirdPartyCodePrefix = $thirdPartyCodePrefix;

        return $this;
    }

    /**
     * Rang du serveur.
     */
    public function getServerRank(): ?string
    {
        return $this->serverRank;
    }

    /**
     * Rang du serveur.
     */
    public function setServerRank(?string $serverRank): self
    {
        $this->initialized['serverRank'] = true;
        $this->serverRank = $serverRank;

        return $this;
    }

    /**
     * Commission sur encaissement.
     */
    public function getIsCommissionPayment(): ?bool
    {
        return $this->isCommissionPayment;
    }

    /**
     * Commission sur encaissement.
     */
    public function setIsCommissionPayment(?bool $isCommissionPayment): self
    {
        $this->initialized['isCommissionPayment'] = true;
        $this->isCommissionPayment = $isCommissionPayment;

        return $this;
    }

    /**
     * Bloc-notes.
     */
    public function getNotepad(): ?string
    {
        return $this->notepad;
    }

    /**
     * Bloc-notes.
     */
    public function setNotepad(?string $notepad): self
    {
        $this->initialized['notepad'] = true;
        $this->notepad = $notepad;

        return $this;
    }
}
