<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsActionV1ActionKeyThirdParty
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Tiers.
     *
     * @var string|null
     */
    protected $thirdParty;
    /**
     * Numéro d'action par auxiliaire.
     *
     * @var int|null
     */
    protected $number;

    /**
     * Tiers.
     */
    public function getThirdParty(): ?string
    {
        return $this->thirdParty;
    }

    /**
     * Tiers.
     */
    public function setThirdParty(?string $thirdParty): self
    {
        $this->initialized['thirdParty'] = true;
        $this->thirdParty = $thirdParty;

        return $this;
    }

    /**
     * Numéro d'action par auxiliaire.
     */
    public function getNumber(): ?int
    {
        return $this->number;
    }

    /**
     * Numéro d'action par auxiliaire.
     */
    public function setNumber(?int $number): self
    {
        $this->initialized['number'] = true;
        $this->number = $number;

        return $this;
    }
}
