<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsSalesOrderUserDefinedDataDto
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Table libre 1.
     *
     * @var string|null
     */
    protected $userDefinedTable1Code;
    /**
     * Table libre 2.
     *
     * @var string|null
     */
    protected $userDefinedTable2Code;
    /**
     * Table libre 3.
     *
     * @var string|null
     */
    protected $userDefinedTable3Code;
    /**
     * Table libre 4.
     *
     * @var string|null
     */
    protected $userDefinedTable4Code;
    /**
     * Table libre 5.
     *
     * @var string|null
     */
    protected $userDefinedTable5Code;
    /**
     * Table libre 6.
     *
     * @var string|null
     */
    protected $userDefinedTable6Code;
    /**
     * Table libre 7.
     *
     * @var string|null
     */
    protected $userDefinedTable7Code;
    /**
     * Table libre 8.
     *
     * @var string|null
     */
    protected $userDefinedTable8Code;
    /**
     * Table libre 9.
     *
     * @var string|null
     */
    protected $userDefinedTable9Code;
    /**
     * Table libre 10.
     *
     * @var string|null
     */
    protected $userDefinedTable10Code;

    /**
     * Table libre 1.
     */
    public function getUserDefinedTable1Code(): ?string
    {
        return $this->userDefinedTable1Code;
    }

    /**
     * Table libre 1.
     */
    public function setUserDefinedTable1Code(?string $userDefinedTable1Code): self
    {
        $this->initialized['userDefinedTable1Code'] = true;
        $this->userDefinedTable1Code = $userDefinedTable1Code;

        return $this;
    }

    /**
     * Table libre 2.
     */
    public function getUserDefinedTable2Code(): ?string
    {
        return $this->userDefinedTable2Code;
    }

    /**
     * Table libre 2.
     */
    public function setUserDefinedTable2Code(?string $userDefinedTable2Code): self
    {
        $this->initialized['userDefinedTable2Code'] = true;
        $this->userDefinedTable2Code = $userDefinedTable2Code;

        return $this;
    }

    /**
     * Table libre 3.
     */
    public function getUserDefinedTable3Code(): ?string
    {
        return $this->userDefinedTable3Code;
    }

    /**
     * Table libre 3.
     */
    public function setUserDefinedTable3Code(?string $userDefinedTable3Code): self
    {
        $this->initialized['userDefinedTable3Code'] = true;
        $this->userDefinedTable3Code = $userDefinedTable3Code;

        return $this;
    }

    /**
     * Table libre 4.
     */
    public function getUserDefinedTable4Code(): ?string
    {
        return $this->userDefinedTable4Code;
    }

    /**
     * Table libre 4.
     */
    public function setUserDefinedTable4Code(?string $userDefinedTable4Code): self
    {
        $this->initialized['userDefinedTable4Code'] = true;
        $this->userDefinedTable4Code = $userDefinedTable4Code;

        return $this;
    }

    /**
     * Table libre 5.
     */
    public function getUserDefinedTable5Code(): ?string
    {
        return $this->userDefinedTable5Code;
    }

    /**
     * Table libre 5.
     */
    public function setUserDefinedTable5Code(?string $userDefinedTable5Code): self
    {
        $this->initialized['userDefinedTable5Code'] = true;
        $this->userDefinedTable5Code = $userDefinedTable5Code;

        return $this;
    }

    /**
     * Table libre 6.
     */
    public function getUserDefinedTable6Code(): ?string
    {
        return $this->userDefinedTable6Code;
    }

    /**
     * Table libre 6.
     */
    public function setUserDefinedTable6Code(?string $userDefinedTable6Code): self
    {
        $this->initialized['userDefinedTable6Code'] = true;
        $this->userDefinedTable6Code = $userDefinedTable6Code;

        return $this;
    }

    /**
     * Table libre 7.
     */
    public function getUserDefinedTable7Code(): ?string
    {
        return $this->userDefinedTable7Code;
    }

    /**
     * Table libre 7.
     */
    public function setUserDefinedTable7Code(?string $userDefinedTable7Code): self
    {
        $this->initialized['userDefinedTable7Code'] = true;
        $this->userDefinedTable7Code = $userDefinedTable7Code;

        return $this;
    }

    /**
     * Table libre 8.
     */
    public function getUserDefinedTable8Code(): ?string
    {
        return $this->userDefinedTable8Code;
    }

    /**
     * Table libre 8.
     */
    public function setUserDefinedTable8Code(?string $userDefinedTable8Code): self
    {
        $this->initialized['userDefinedTable8Code'] = true;
        $this->userDefinedTable8Code = $userDefinedTable8Code;

        return $this;
    }

    /**
     * Table libre 9.
     */
    public function getUserDefinedTable9Code(): ?string
    {
        return $this->userDefinedTable9Code;
    }

    /**
     * Table libre 9.
     */
    public function setUserDefinedTable9Code(?string $userDefinedTable9Code): self
    {
        $this->initialized['userDefinedTable9Code'] = true;
        $this->userDefinedTable9Code = $userDefinedTable9Code;

        return $this;
    }

    /**
     * Table libre 10.
     */
    public function getUserDefinedTable10Code(): ?string
    {
        return $this->userDefinedTable10Code;
    }

    /**
     * Table libre 10.
     */
    public function setUserDefinedTable10Code(?string $userDefinedTable10Code): self
    {
        $this->initialized['userDefinedTable10Code'] = true;
        $this->userDefinedTable10Code = $userDefinedTable10Code;

        return $this;
    }
}
