<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class CegidMtsTechnicalBasesModelsSmartServiceResult
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Xml contenant les opérations traités enrichi par le traitement. Les retours de données sont contenus dans cette propriété.
     *
     * @var string|null
     */
    protected $rawXml;
    /**
     * Résultats obtenus par les divers opérations.
     *
     * @var string|null
     */
    protected $result;

    /**
     * Xml contenant les opérations traités enrichi par le traitement. Les retours de données sont contenus dans cette propriété.
     */
    public function getRawXml(): ?string
    {
        return $this->rawXml;
    }

    /**
     * Xml contenant les opérations traités enrichi par le traitement. Les retours de données sont contenus dans cette propriété.
     */
    public function setRawXml(?string $rawXml): self
    {
        $this->initialized['rawXml'] = true;
        $this->rawXml = $rawXml;

        return $this;
    }

    /**
     * Résultats obtenus par les divers opérations.
     */
    public function getResult(): ?string
    {
        return $this->result;
    }

    /**
     * Résultats obtenus par les divers opérations.
     */
    public function setResult(?string $result): self
    {
        $this->initialized['result'] = true;
        $this->result = $result;

        return $this;
    }
}
