<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class MicrosoftODataEdmExpressionsIEdmPathExpression
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<string>|null
     */
    protected $path;
    /**
     * @var string|null
     */
    protected $expressionKind;

    /**
     * @return list<string>|null
     */
    public function getPath(): ?array
    {
        return $this->path;
    }

    /**
     * @param list<string>|null $path
     */
    public function setPath(?array $path): self
    {
        $this->initialized['path'] = true;
        $this->path = $path;

        return $this;
    }

    public function getExpressionKind(): ?string
    {
        return $this->expressionKind;
    }

    public function setExpressionKind(?string $expressionKind): self
    {
        $this->initialized['expressionKind'] = true;
        $this->expressionKind = $expressionKind;

        return $this;
    }
}
