<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class MicrosoftODataEdmIEdmStructuredType
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var bool|null
     */
    protected $isAbstract;
    /**
     * @var bool|null
     */
    protected $isOpen;
    /**
     * @var MicrosoftODataEdmIEdmStructuredType|null
     */
    protected $baseType;
    /**
     * @var list<MicrosoftODataEdmIEdmProperty>|null
     */
    protected $declaredProperties;
    /**
     * @var string|null
     */
    protected $typeKind;

    public function getIsAbstract(): ?bool
    {
        return $this->isAbstract;
    }

    public function setIsAbstract(?bool $isAbstract): self
    {
        $this->initialized['isAbstract'] = true;
        $this->isAbstract = $isAbstract;

        return $this;
    }

    public function getIsOpen(): ?bool
    {
        return $this->isOpen;
    }

    public function setIsOpen(?bool $isOpen): self
    {
        $this->initialized['isOpen'] = true;
        $this->isOpen = $isOpen;

        return $this;
    }

    public function getBaseType(): ?self
    {
        return $this->baseType;
    }

    public function setBaseType(?self $baseType): self
    {
        $this->initialized['baseType'] = true;
        $this->baseType = $baseType;

        return $this;
    }

    /**
     * @return list<MicrosoftODataEdmIEdmProperty>|null
     */
    public function getDeclaredProperties(): ?array
    {
        return $this->declaredProperties;
    }

    /**
     * @param list<MicrosoftODataEdmIEdmProperty>|null $declaredProperties
     */
    public function setDeclaredProperties(?array $declaredProperties): self
    {
        $this->initialized['declaredProperties'] = true;
        $this->declaredProperties = $declaredProperties;

        return $this;
    }

    public function getTypeKind(): ?string
    {
        return $this->typeKind;
    }

    public function setTypeKind(?string $typeKind): self
    {
        $this->initialized['typeKind'] = true;
        $this->typeKind = $typeKind;

        return $this;
    }
}
