<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class MicrosoftODataEdmIEdmTypeReference
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var bool|null
     */
    protected $isNullable;
    /**
     * @var MicrosoftODataEdmIEdmType|null
     */
    protected $definition;

    public function getIsNullable(): ?bool
    {
        return $this->isNullable;
    }

    public function setIsNullable(?bool $isNullable): self
    {
        $this->initialized['isNullable'] = true;
        $this->isNullable = $isNullable;

        return $this;
    }

    public function getDefinition(): ?MicrosoftODataEdmIEdmType
    {
        return $this->definition;
    }

    public function setDefinition(?MicrosoftODataEdmIEdmType $definition): self
    {
        $this->initialized['definition'] = true;
        $this->definition = $definition;

        return $this;
    }
}
