<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class MicrosoftODataCoreUriParserSemanticSelectExpandClause
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var list<MicrosoftODataCoreUriParserSemanticSelectItem>|null
     */
    protected $selectedItems;
    /**
     * @var bool|null
     */
    protected $allSelected;

    /**
     * @return list<MicrosoftODataCoreUriParserSemanticSelectItem>|null
     */
    public function getSelectedItems(): ?array
    {
        return $this->selectedItems;
    }

    /**
     * @param list<MicrosoftODataCoreUriParserSemanticSelectItem>|null $selectedItems
     */
    public function setSelectedItems(?array $selectedItems): self
    {
        $this->initialized['selectedItems'] = true;
        $this->selectedItems = $selectedItems;

        return $this;
    }

    public function getAllSelected(): ?bool
    {
        return $this->allSelected;
    }

    public function setAllSelected(?bool $allSelected): self
    {
        $this->initialized['allSelected'] = true;
        $this->allSelected = $allSelected;

        return $this;
    }
}
