<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class SystemCollectionsGenericKeyValuePairSystemStringSystemString
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string|null
     */
    protected $key;
    /**
     * @var string|null
     */
    protected $value;
    /**
     * @var mixed|null
     */
    protected $key2;
    /**
     * @var mixed|null
     */
    protected $value2;

    public function getKey(): ?string
    {
        return $this->key;
    }

    public function setKey(?string $key): self
    {
        $this->initialized['key'] = true;
        $this->key = $key;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(?string $value): self
    {
        $this->initialized['value'] = true;
        $this->value = $value;

        return $this;
    }

    public function getKey2()
    {
        return $this->key2;
    }

    public function setKey2($key2): self
    {
        $this->initialized['key2'] = true;
        $this->key2 = $key2;

        return $this;
    }

    public function getValue2()
    {
        return $this->value2;
    }

    public function setValue2($value2): self
    {
        $this->initialized['value2'] = true;
        $this->value2 = $value2;

        return $this;
    }
}
