<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class SystemWebODataRoutingODataPath
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var MicrosoftODataEdmIEdmType|null
     */
    protected $edmType;
    /**
     * @var MicrosoftODataEdmIEdmNavigationSource|null
     */
    protected $navigationSource;
    /**
     * @var string|null
     */
    protected $pathTemplate;
    /**
     * @var list<SystemWebODataRoutingODataPathSegment>|null
     */
    protected $segments;

    public function getEdmType(): ?MicrosoftODataEdmIEdmType
    {
        return $this->edmType;
    }

    public function setEdmType(?MicrosoftODataEdmIEdmType $edmType): self
    {
        $this->initialized['edmType'] = true;
        $this->edmType = $edmType;

        return $this;
    }

    public function getNavigationSource(): ?MicrosoftODataEdmIEdmNavigationSource
    {
        return $this->navigationSource;
    }

    public function setNavigationSource(?MicrosoftODataEdmIEdmNavigationSource $navigationSource): self
    {
        $this->initialized['navigationSource'] = true;
        $this->navigationSource = $navigationSource;

        return $this;
    }

    public function getPathTemplate(): ?string
    {
        return $this->pathTemplate;
    }

    public function setPathTemplate(?string $pathTemplate): self
    {
        $this->initialized['pathTemplate'] = true;
        $this->pathTemplate = $pathTemplate;

        return $this;
    }

    /**
     * @return list<SystemWebODataRoutingODataPathSegment>|null
     */
    public function getSegments(): ?array
    {
        return $this->segments;
    }

    /**
     * @param list<SystemWebODataRoutingODataPathSegment>|null $segments
     */
    public function setSegments(?array $segments): self
    {
        $this->initialized['segments'] = true;
        $this->segments = $segments;

        return $this;
    }
}
