<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Cegid\Api\Model;

class SystemWebODataQueryODataQueryOptionsCegidMtsProductEntityV1ProductDtoReader
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var mixed|null
     */
    protected $ifMatch;
    /**
     * @var mixed|null
     */
    protected $ifNoneMatch;
    /**
     * @var SystemWebODataODataQueryContext|null
     */
    protected $context;
    /**
     * @var SystemWebODataQueryODataQueryOptionsCegidMtsProductEntityV1ProductDtoReaderRequest|null
     */
    protected $request;
    /**
     * @var SystemWebODataQueryODataRawQueryOptions|null
     */
    protected $rawValues;
    /**
     * @var SystemWebODataQuerySelectExpandQueryOption|null
     */
    protected $selectExpand;
    /**
     * @var SystemWebODataQueryApplyQueryOption|null
     */
    protected $apply;
    /**
     * @var SystemWebODataQueryFilterQueryOption|null
     */
    protected $filter;
    /**
     * @var SystemWebODataQueryOrderByQueryOption|null
     */
    protected $orderBy;
    /**
     * @var SystemWebODataQuerySkipQueryOption|null
     */
    protected $skip;
    /**
     * @var SystemWebODataQueryTopQueryOption|null
     */
    protected $top;
    /**
     * @var SystemWebODataQueryCountQueryOption|null
     */
    protected $count;
    /**
     * @var SystemWebODataQueryValidatorsODataQueryValidator|null
     */
    protected $validator;

    public function getIfMatch()
    {
        return $this->ifMatch;
    }

    public function setIfMatch($ifMatch): self
    {
        $this->initialized['ifMatch'] = true;
        $this->ifMatch = $ifMatch;

        return $this;
    }

    public function getIfNoneMatch()
    {
        return $this->ifNoneMatch;
    }

    public function setIfNoneMatch($ifNoneMatch): self
    {
        $this->initialized['ifNoneMatch'] = true;
        $this->ifNoneMatch = $ifNoneMatch;

        return $this;
    }

    public function getContext(): ?SystemWebODataODataQueryContext
    {
        return $this->context;
    }

    public function setContext(?SystemWebODataODataQueryContext $context): self
    {
        $this->initialized['context'] = true;
        $this->context = $context;

        return $this;
    }

    public function getRequest(): ?SystemWebODataQueryODataQueryOptionsCegidMtsProductEntityV1ProductDtoReaderRequest
    {
        return $this->request;
    }

    public function setRequest(?SystemWebODataQueryODataQueryOptionsCegidMtsProductEntityV1ProductDtoReaderRequest $request): self
    {
        $this->initialized['request'] = true;
        $this->request = $request;

        return $this;
    }

    public function getRawValues(): ?SystemWebODataQueryODataRawQueryOptions
    {
        return $this->rawValues;
    }

    public function setRawValues(?SystemWebODataQueryODataRawQueryOptions $rawValues): self
    {
        $this->initialized['rawValues'] = true;
        $this->rawValues = $rawValues;

        return $this;
    }

    public function getSelectExpand(): ?SystemWebODataQuerySelectExpandQueryOption
    {
        return $this->selectExpand;
    }

    public function setSelectExpand(?SystemWebODataQuerySelectExpandQueryOption $selectExpand): self
    {
        $this->initialized['selectExpand'] = true;
        $this->selectExpand = $selectExpand;

        return $this;
    }

    public function getApply(): ?SystemWebODataQueryApplyQueryOption
    {
        return $this->apply;
    }

    public function setApply(?SystemWebODataQueryApplyQueryOption $apply): self
    {
        $this->initialized['apply'] = true;
        $this->apply = $apply;

        return $this;
    }

    public function getFilter(): ?SystemWebODataQueryFilterQueryOption
    {
        return $this->filter;
    }

    public function setFilter(?SystemWebODataQueryFilterQueryOption $filter): self
    {
        $this->initialized['filter'] = true;
        $this->filter = $filter;

        return $this;
    }

    public function getOrderBy(): ?SystemWebODataQueryOrderByQueryOption
    {
        return $this->orderBy;
    }

    public function setOrderBy(?SystemWebODataQueryOrderByQueryOption $orderBy): self
    {
        $this->initialized['orderBy'] = true;
        $this->orderBy = $orderBy;

        return $this;
    }

    public function getSkip(): ?SystemWebODataQuerySkipQueryOption
    {
        return $this->skip;
    }

    public function setSkip(?SystemWebODataQuerySkipQueryOption $skip): self
    {
        $this->initialized['skip'] = true;
        $this->skip = $skip;

        return $this;
    }

    public function getTop(): ?SystemWebODataQueryTopQueryOption
    {
        return $this->top;
    }

    public function setTop(?SystemWebODataQueryTopQueryOption $top): self
    {
        $this->initialized['top'] = true;
        $this->top = $top;

        return $this;
    }

    public function getCount(): ?SystemWebODataQueryCountQueryOption
    {
        return $this->count;
    }

    public function setCount(?SystemWebODataQueryCountQueryOption $count): self
    {
        $this->initialized['count'] = true;
        $this->count = $count;

        return $this;
    }

    public function getValidator(): ?SystemWebODataQueryValidatorsODataQueryValidator
    {
        return $this->validator;
    }

    public function setValidator(?SystemWebODataQueryValidatorsODataQueryValidator $validator): self
    {
        $this->initialized['validator'] = true;
        $this->validator = $validator;

        return $this;
    }
}
